### ISSUE TITLE
Setting Networked Properties in a Networked BaseNetworkable on a Entity after Construction doesn't work.

### ISSUE THREAD

**Issue by Adesii** [Facepunch/sbox-issues#1009]
what a title huh

**Describe the bug**
When Creating a new Entity and setting a Networked property in a Networked BaseNetworkable in the same function on that Entity the changed properties are just ignored

Basically if i create a new Entity and it has a Networked Property of a Custom BaseNetworkable
and i try to change a Networked Value on the BaseNetworkable
the changes are simply ignored.

Entity
   -> Networked BaseNetworkable
   -----> Networked Value (cant set after creating the entity)

But this works if i create my own INetworkSerializer on the BaseNetworkable and call the WriteNetworkData function
so it should also work automatically right?

this might be a issue with the autogenerated [Net] since its not just that is isn't networked. it isn't set it at all.

```cs
[Net] public BrokenClass BrokenClass { get; set; } // these are on a Entity with Transmit to All
[Net] public WorkingClass WorkingClass { get; set; }

BrokenEntity be = new();
be.BrokenClass = new() // this is simply ignored
{
	Number = 100,
};

be.BrokenClass.WriteNetworkData(); // Not needed i know. but wanted to make it the same like the working class

be.WorkingClass = new() // this works just fine
{
	Number = 99
};
be.WorkingClass.WriteNetworkData();

Log.Info( $"BrokenClass On Server: {be.BrokenClass.Number}" ); // returns -1 the default value
Log.Info( $"WorkingClass On Server: {be.WorkingClass.Number}" ); // returns 99 just fine

//in a client rpc

Log.Info( $"BrokenClass On Client: {BrokenClass.Number}" ); // returns -1 the default value
Log.Info( $"WorkingClass On Client: {WorkingClass.Number}" );// returns 99 just fine



public partial class BrokenClass : BaseNetworkable
{
	[Net] public int Number { get; set; } = -1;
}

public partial class WorkingClass : BaseNetworkable, INetworkSerializer
{
	public int Number { get; set; } = -1;

	public void Read( NetRead read )
	{
		Number = read.Read<int>();
	}

	public void Write( NetWrite write )
	{
		write.Write( Number );
	}
}
```

**To Reproduce**

[brokennetworking.zip](https://github.com/Facepunch/sbox-issues/files/7253091/brokennetworking.zip)

1. Download Minimal Example
2. Open it
3. Click the Button
4. See that the BrokenClass doesn't work at all but the WorkingClass works just fine

**Expected behavior**
It should just Network and set the Value just fine since it works if making a custom Serializer.

**Comment by DevulTj** [comment]
This also applies to Entities with [Net] variables on them too. Anything before Spawn just won't stick.

**Comment by garrynewman** [comment]
Should be fixed in 10 mins

**Comment by Adesii** [comment]
Well it isn't ignored anymore but it is still not Networking the Value Even after waiting like a second or so

**Comment by Adesii** [comment]
https://user-images.githubusercontent.com/37816311/135304602-038ccd6f-e23e-45e8-b9e2-5f12f8522e28.mp4

^ here is the example i made with a async on the clientrpc of 1000ms

**Comment by Adesii** [comment]
@garrynewman the original issue seems to be fixed. tho the set value is never networked.

**Comment by garrynewman** [comment]
This is working okay for me now - if you can give me some code that isn't working I'll reopen

**Comment by Adesii** [comment]
weird. i just tested it with the `Changed when client creates network tables` commit and it still doesn't network the Number correctly

https://user-images.githubusercontent.com/37816311/135829388-c443fdf7-ae02-4a03-b4e1-4a28d2bc3e10.mp4

it still defaults to -1 on the client side. with the same zip as in the original bug.

i have a separate version of the above zip that just checks the client sided number every tick and it never gets networked. it only gets networked if i set a different number like 101.

**Comment by Adesii** [comment]
ok, issue seems to be finally fixed after the `Fix client not reading all variables` commit.

**Comment by garrynewman** [comment]
<3 thanks for the update
