### ISSUE TITLE
Backspace in text entries moves the caret back 2 positions

### ISSUE THREAD

**Issue by goaaats** [Facepunch/sbox-issues#1459]
**Describe the bug**
When pressing backspace in any text entry with text, if the caret is at the end of the line, it will jump back 2 positions instead of one.
Occasionally, an exception is produced.

![image](https://user-images.githubusercontent.com/16760685/148226486-ada7fffa-b299-4345-a9c3-a8660e853277.png)

**To Reproduce**

1. Open the console or the "control zoo" part of the UI tests
2. Type something in the console input or the text entry
3. Position the caret at the end of your input and press backspace

**Expected behavior**
The last character of the text should be removed and the caret should remain at the end of the input

**Screenshots**
![sbox_AsxI9iUFcT](https://user-images.githubusercontent.com/16760685/148226762-f23098a3-e52c-4fa1-80ac-1c3da0421000.gif)

**Additional context**
I have a Japanese IME installed, but it's not being used in this example.

**Comment by cr4yz** [comment]
Should be fixed in the next update

**Comment by goaaats** [comment]
Sure enough, I still get exceptions when typing, but I assume they're unrelated then
![image](https://user-images.githubusercontent.com/16760685/149053189-bbc24a10-abe0-4127-aa19-bc990a3a87a1.png)

**Comment by cr4yz** [comment]
> 

Yep this is unrelated.  Are you receiving this exception with the "History With Cookie" TextEntry under UI tests?
