### ISSUE TITLE
Enabling a Addon does not load Assets if it was Disabled on Startup

### ISSUE THREAD

**Issue by Adesii** [Facepunch/sbox-issues#1520]
**Describe the bug**
If the Addon was Disabled on startup and is Enabled afterwards it doesn't load the Assets from that Addon until a Restart with the Addon enabled.

**To Reproduce**

1. Start S&Box
2. Disable an Addon with Assets in it
3. Close S&Box
4. Open S&Box again
5. Enable that Addon.
6. See that the Assets didn't load 

**Expected behavior**
It should load the Assets upon Enabling it and not only on Startup.

**Comment by garrynewman** [comment]
This should be fixed on the next build

**Comment by Adesii** [comment]
It still doesn't seem to work correctly. here is an example video of it not working.
The Sbox Minigolf addon is the one by Matt, so it definitely has assets in it

https://user-images.githubusercontent.com/37816311/149951957-9ce9aa7b-614f-43cd-9ea3-eff5f449d751.mp4

**Comment by DoctorGurke** [comment]
it's definitely mounting the assets into the game itself, but the assetbrowser isn't being updated with the new assets

**Comment by Adesii** [comment]
![18,01_21,13 06_7cb](https://user-images.githubusercontent.com/37816311/150011505-9cca9410-f779-4fd4-a55b-e9785f3f99fe.png)
hmm.. i sometimes also get this error when enabling a addon. not sure if its related to this issue. but it only seems to be happening when the addon was disabled on startup

**Comment by Adesii** [comment]
This seems to be now fixed in the latest release. i atleast didn't encounter it anymore.
