### ISSUE TITLE
Output<T> doesn't parse correctly when T is an enum.

### ISSUE THREAD

**Issue by kolexxx** [Facepunch/sbox-issues#1541]
**Describe the bug**
Output<T> doesn't parse correctly when T is an enum.

**To Reproduce**

Download 
[minimal_example.zip](https://github.com/Facepunch/sbox-issues/files/7952390/minimal_example.zip)

**Expected behavior**
It should parse correctly or at least have it be documented which types we can parse.

**Additional context**
``FGD Parse error:  Error parsing class 'me_bug'``

**Comment by robotboy655** [comment]
Should be fixed when the game next updates.

**Comment by kolexxx** [comment]
sadly, it still doesn't show up in the minimal example in my case :(
``FGD Parse error:  near ':' - Bad input/output type 'choices'``

**Comment by robotboy655** [comment]
You need to launch the gamemode once for the fgd to regenerate, after that (after a game restart) it should be fine as it will be loading the new .fgd that has the correct output type.

**Comment by kolexxx** [comment]
yeah, my bad. works as intended
