### ISSUE TITLE
Map.Reset() crashes the game after several calls

### ISSUE THREAD

**Issue by kolexxx** [Facepunch/sbox-issues#1677]
**Describe the bug**
`Map.Reset()` crashes the game after several calls. This could possibly be tied to https://github.com/Facepunch/sbox-issues/issues/1646.

**To Reproduce**

1.  Launch up the Sandbox gamemode
2. Destroy some windows or props
3. Call `respawn_entities`
4. Repeat

**Additional context**
https://drive.google.com/file/d/1txNTszPFNZAu5WmiTnrp08EL61cAG3u_/view?usp=sharing

The fps gets lower each time the command is called, further tying this issue to https://github.com/Facepunch/sbox-issues/issues/1646.

**Comment by robotboy655** [comment]
I have fixed the FPS dropping, the crashing seems to be due to light entities, will look into it.

**Comment by robotboy655** [comment]
Crashes should also be fixed now.

**Comment by kolexxx** [comment]
The crashes seem to mostly be fixed, but it still happens on large enough maps. I will send you a crash dump when it crashes again.

**Comment by kolexxx** [comment]
[Log.zip](https://github.com/Facepunch/sbox-issues/files/8457586/Log.zip)

Most recent crash log we got on `ice.terminal`

**Comment by robotboy655** [comment]
That console log is not helpful in this case unfortunately, I will need a `.dmp`/`.mdmp` file to look into the crash.

**Comment by mzegar** [comment]
[sbox_2022_0416_150743_0_accessviolation.zip](https://github.com/Facepunch/sbox-issues/files/8500751/sbox_2022_0416_150743_0_accessviolation.zip)
Might be related?

**Comment by robotboy655** [comment]
Might be, however it appears to be some sort of memory corruption which would not be possible for me to debug from a single dump.
