### ISSUE TITLE
ConVar.Replicated neither replicated nor stored on host client

### ISSUE THREAD

**Issue by DoctorGurke** [Facepunch/sbox-issues#1856]
### Describe the bug

Since the last pain day, ConVar.Replicated no longer replicates to the client realm or connected clients and is not stored locally on the host client when restarting. (game session via `restart`, not full game restart)

### To Reproduce

1. Make a ConVar.Replicated property
2. set it via console and check its state on the server and client realm
3. note it doesn't update for the client
4. type `restart` into the console
5. note it doesn't persist between session restarts

### Expected behavior

It should be replicating to the local client and connected clients and be stored locally on the host.

### Additional context

#1112 This was an additional issue that is still not working, especially since replication is completely broken now.

**Comment by garrynewman** [comment]
I think I fixed this, but please let me know if I didn't.

**Comment by DoctorGurke** [comment]
it's still not storing when using `restart` etc I'm afraid, it is however replicating to clients now
