### ISSUE TITLE
Inheriting from `PathPlatformEntity` removes ability for new entity to follow paths.

### ISSUE THREAD

**Issue by Fortune117** [Facepunch/sbox-issues#1942]
### Describe the bug

When inheriting from a `PathPlatformEntity`, the new entity seems unable to follow paths as expected. I've attached a vmap and a test entity for example purposes.

```CS

[HammerEntity]
[EditorModel("entities/drone/drone.vmdl")]
public class AnomalyComet : PathPlatformEntity
{
    public override void Spawn()
    {
        base.Spawn();
        SetModel("entities/drone/drone.vmdl");
    }
}
```

### To Reproduce

1. Compile and open the vmap
2. Entity will not follow the path despite being configured to

### Expected behavior

The entity follows the behaviour of `PathPlatformEntity`.

### Media/Files

[test.zip](https://github.com/Facepunch/sbox-issues/files/8919338/test.zip) - vmap
[AnomalyComet.zip](https://github.com/Facepunch/sbox-issues/files/8919342/AnomalyComet.zip) - entity

**Comment by robotboy655** [comment]
Should be fixed when the game next updates.

It's down to events of base classes not working if they are private methods.

**Comment by Fortune117** [comment]
Just tested it now after updating and it still isn't working. Recompiled the map and gamemode.

**Comment by robotboy655** [comment]
No recompilation needed, it's an engine change. It should be working though.

Does using `ent_text` on it show the path or the sphere helpers?
![image](https://user-images.githubusercontent.com/3299036/174116127-9de8ec22-aba7-44b4-9228-b73e5d831a22.png)

**Comment by Fortune117** [comment]
Using ent_text with the name of the path gave me this:
![image](https://user-images.githubusercontent.com/7847372/174117749-5540a148-1b8a-428d-8927-56de2bc075de.png)

Didn't show the path or helpers

**Comment by robotboy655** [comment]
Can you verify your game and test the exact stuff you provided in the issue above?

**Comment by robotboy655** [comment]
Oh, that's my bad, should work when the game next updates.

**Comment by Fortune117** [comment]
Just woke up and confirmed it works, thanks 👍
