### ISSUE TITLE
Failed to join game and, a little later, format of .exe/.dll is invalid

### ISSUE THREAD

**Issue by thegrb93** [Facepunch/sbox-issues#287]
**Describe the bug**

Compilation of my addon succeeds but silently fails to join the game causing a disconnect.
Then a little later, 'Format of exe or dll is invalid' appears. (This might just be caused by the initial fail)

**To Reproduce**

Added these to whitelist manually: https://github.com/Facepunch/sbox-issues/issues/275
Copy my addon to addons and make sandbox depend on it: https://github.com/thegrb93/StarfallSBox
Try to run sandbox with the dependency on my addon.
 
**Expected behavior**

The game loads into sandbox without any error.

**Screenshots**

![image](https://user-images.githubusercontent.com/6713261/120174397-0c169980-c1d3-11eb-9044-8ee147a11b0b.png)

**Additional context**

I have the game installed under I:\. so maybe related https://github.com/Facepunch/sbox-issues/issues/262

**Comment by thegrb93** [comment]
Also I forgot to mention that if I delete https://github.com/thegrb93/StarfallSBox/tree/master/code/kopilua then it works. So it seems either files nested too deeply, or something in the Kopilua library is causing the issue.

**Comment by birdbrainswagtrain** [comment]
Howdy! I've run into this as well - I believe I was actually trying to use the same library - and I think I've made some headway debugging it.

From what I can tell, it's caused by some limitations of the stringtable entries that assemblies are crammed into.

Using assemblies much larger than ~120kb results in a BadImageFormatException - the client tries to load an empty assembly - and a somewhat unhelpful "Joining failed.. disconnecting" message.

Hotloading assemblies seems to allow larger files, up to ~500kb before disconnecting players with NETWORK_DISCONNECT_STRINGTABLEMSG_OVERFLOW.

On the extreme side, assemblies larger than ~1MB will just crash the game with a popup about the limit being reached.

These limits aren't outside the realm of possibility for larger games, especially since debug info seems to be included in the stringtable entry.

To reproduce, you can just chuck either of these files in an addon:
http://tmp.bz/Huge_200K.cs
http://tmp.bz/Huge_1M.cs

**Comment by thegrb93** [comment]
Sounds very plausible. Thanks for figuring that out

**Comment by aylaylay** [comment]
I think I ran into this very early on

**Comment by garrynewman** [comment]
I've increased the max payload. This should solve this particular problem, but it's not completely out of the question that another problem will pop up out of it.

**Comment by garrynewman** [comment]
This should be fixed/added on next build, which usually takes about 5 minutes to hit Steam. Please reply to this post to let me know if it's fixed. 

If it is fixed feel free to close the issue yourself <3

**Comment by thegrb93** [comment]
I think I'm still hitting the limit

![image](https://user-images.githubusercontent.com/6713261/121798253-3dd82900-cbf3-11eb-9b6d-9a74ac4a9697.png)

**Comment by birdbrainswagtrain** [comment]
Yeah, I'm still running into the same issue with the smaller of my test files.

**Comment by Nebual** [comment]
I'm still running into this on the latest build. The limit seems to be approximately 200kb of _compressed_ `.cs` files, including comments, as its evidently networking the raw uncompiled source.

Was very confusing to debug; I ran into it naturally (I don't have any large libraries or anything, but base Sandbox is already a third of that limit), and found _deleting comments_ finally made the cryptic error stop 😅

**Comment by Nebual** [comment]
As of today's update, the reported obscure error is fixed; there's a new limit (with a clearer message) at ~3mb reproducible using Huge_1M.cs, but this is an improvement!

**Comment by thegrb93** [comment]
Hope that's enough to at least be able to finally test my stuff. 3000kb is still not very much.

**Comment by Nebual** [comment]
I spoke too soon, the _host_ can now connect, but additional clients (including a second `sbox.exe -multirun` instance) fail to connect when using `Huge_200K.cs`, they just hang on Client Startup for several minutes before DC'ing.

On the host I see:
> MuffinTastic SendMessage reliable failed with EResult: 8, bytes written 524373

**Comment by Leafdroid** [comment]
This issue is still bothering me on a daily basis, I keep having to throw out a large amount of the game files in order for my friends to be able join which makes testing painful as I can't test everything at once. 😕

**Comment by garrynewman** [comment]
Okay - I think I made this a bunch more bulletproof. Give it a go now please.

**Comment by Geeknerd1337** [comment]
Tested and seems to work perfectly now, thank you!
