### ISSUE TITLE
Hammer-Like Autosaves in Scenes

### ISSUE THREAD

**Issue by DrakeFruit** [Facepunch/sbox-issues#4260]
### For?

S&Box

### What can't you do?

With how often scenes crash or don't save properly (usually when there's an internal error I think) it's really frustrating to not have any autosaves.

### How would you like it to work?

A gui with the option to set a path for the autosaves, the interval they're saved at, and a drop down list of all the autosaves with dates that you can click to load. Saving while an auto save is loaded as a scene would prompt you if you're sure you want to override the current save.

### What have you tried?

I've tried saving as often as possible but every once in a while I'll run into an error, restart s&box to fix the error, and my scene will be reverted to how it was when I first opened it that session.

**Comment by garrynewman** [comment]
Lets make it not crash

**Comment by DrakeFruit** [comment]
huh?? It's still a feature I want it's not purely because of how often it crashes. This isn't completed?

**Comment by handsomematt** [comment]
> I'll run into an error, restart s&box to fix the error, and my scene will be reverted to how it was when I first opened it that session

surely this is better solved by #4239 then

**Comment by DrakeFruit** [comment]
> > I'll run into an error, restart s&box to fix the error, and my scene will be reverted to how it was when I first opened it that session
> 
> surely this is better solved by #4239 then

sure but you still can't guarantee it will never crash, seems like you guys are actively trying to avoid autosaves for whatever reason? which have saved my ass in hammer so many times.
