### ISSUE TITLE
`SceneTraceResult.GameObject` is empty of components when the trace hits a hitbox

### ISSUE THREAD

**Issue by Fortune117** [Facepunch/sbox-issues#4375]
### Describe the bug

i'm getting the object I hit with my trace like this:

```CS
	var tr = Scene.Trace.Ray( Transform.World.PointToWorld( Center1 ), Transform.World.PointToWorld( Center2 ) )
		.WithoutTags( "nohit" )
		.UseHitboxes()
		.IgnoreGameObjectHierarchy( ignoreTarget )
		.Radius( Radius )
		.Run();

            if ( !tr.Hit )
                continue;
             
            if (tr.GameObject is null)
                continue;
            
            Log.Info( tr.GameObject );
            Log.Info( tr.GameObject.Components.GetAll().Count() );
```
the game object isn't null but it says it has no components on it.

Seems to be specifically hapen when the game object is detected by a trace that hits a hitbox. It works fine when the trace hits a physics shape.

Video to show the output log when it hits physics shape vs hitboxes:

https://github.com/Facepunch/sbox-issues/assets/7847372/96bd0a3c-ceab-4588-86d2-4ef54c91c332

### To Reproduce

1. fire a trace at a gameobject using hitboxes
2. print the components on the tr.GameObject

### Expected behavior

Should return the real game object, it's almost like it's returning a fake or proxy somehow.

**Comment by Fortune117** [comment]
I think I've figured out what it is.

In my prefab the target of the hitbox component is the root of the prefab:
![image](https://github.com/Facepunch/sbox-issues/assets/7847372/5460f2d2-e510-44c6-97f2-6f9414b90373)

![image](https://github.com/Facepunch/sbox-issues/assets/7847372/61ecc4f5-70f9-4270-ad2c-2a3a069df276)

So it's returning the target as the prefabs game object rather than the one that actually exists in the scene. If I unlink the prefab and target the skeleton game object it works again.

**Comment by dch-GH** [comment]
> I think I've figured out what it is.
> 
> In my prefab the target of the hitbox component is the root of the prefab: ![image](https://private-user-images.githubusercontent.com/7847372/294221188-5460f2d2-e510-44c6-97f2-6f9414b90373.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ0MDgyOTUsIm5iZiI6MTcwNDQwNzk5NSwicGF0aCI6Ii83ODQ3MzcyLzI5NDIyMTE4OC01NDYwZjJkMi1lNTEwLTQ0YzYtOTdmMi02Zjk0MTRiOTAzNzMucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDEwNCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAxMDRUMjIzOTU1WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NWQ2MGJiNWIxNThkZjJiNDBlODdlYjJjODIzMjY4ZDU0YjdiYmIwZjI4MTRjZmYzMWM4NTY5MWQ1MTIwOTQ2MyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.sc9GsyLo7eJhm6wsxfQfAAmu_XA2x7P79tb7P6TD_uY)
> 
> ![image](https://private-user-images.githubusercontent.com/7847372/294221497-61ecc4f5-70f9-4270-ad2c-2a3a069df276.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ0MDgyOTUsIm5iZiI6MTcwNDQwNzk5NSwicGF0aCI6Ii83ODQ3MzcyLzI5NDIyMTQ5Ny02MWVjYzRmNS03MGY5LTQyNzAtYWQyYy0yYTNhMDY5ZGYyNzYucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDEwNCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAxMDRUMjIzOTU1WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZjNhZWQzMDcwMmE3Yjg1ZmFlMWE3YWZhYzk4ZTg4Mjc1OGRlYjI0MTBjMjRmM2FiNjhmOGU4ODFjMWFjMjBjMCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.GBpzGYkAa_WaTrycJ9q8sWw7miAJ-fjphGg2nfrZsU4)
> 
> So it's returning the target as the prefabs game object rather than the one that actually exists in the scene. If I unlink the prefab and target the skeleton game object it works again.

Yep the same thing happened to me. I ended up manually setting the Target from the Root via a reference to the Hitbox

**Comment by garrynewman** [comment]
I think this is fixed now?

**Comment by Fortune117** [comment]
> I think this is fixed now?
The issue is still there for me..

I don't think this is actually an issue with traces, it's about how references to the root game object on a prefab are serialized. You can see that the target of the hitboxes references the root game object of the prefab, but when the prefab is spawned instead of referencing the newly instantiated objects root, it still references the actual prefabs root.

**Comment by garrynewman** [comment]
Oh I see, so it's a prefab issue
