### ISSUE TITLE
Converting a child GameObject of a prefab to a prefab and overwriting the root GameObject's prefab file bricks the project

### ISSUE THREAD

**Issue by dch-GH** [Facepunch/sbox-issues#4557]
### Describe the bug

Try to make a child of the root of the prefab the new root, get bricked instead

### To Reproduce

1. Create a prefab.
2. Add a child object, save it.
3. Right click the child, Convert To Prefab...
4. Select the same prefab file as the root, essentially making the child the new root object and overwriting the original prefab
5. Brick your project ~~(until you delete the prefab file manually)~~. Turns out that even after you delete the prefab files, if you ever save a new prefab in the same directory as the one that caused the bricking, the editor will crash and crash on opening the project.

### Expected behavior

Maybe add a context menu option to make a child object the new root object

### Media/Files

![image](https://github.com/Facepunch/sbox-issues/assets/66768086/3acca0e7-bc3a-4154-ab3b-f5198137d911)

**Comment by CarsonKompon** [comment]
This seems to have been fixed at some point as I cannot replicate. Any chance you could confirm this?

**Comment by dch-GH** [comment]
> This seems to have been fixed at some point as I cannot replicate. Any chance you could confirm this?

Just tested on commit: `e8ea11c` and the core of the issue still persists. It doesn't brick the project anymore, but following the steps as listed out does crash the editor, and trying to open that prefab afterwards does crash the editor. Trying to delete the prefab crashes the editor.

**Comment by CarsonKompon** [comment]
Could you send a repro project that does this? I could not get it to crash in my experiments.

**Comment by SturnusA** [comment]
same steps no longer crash editor after the new prefab system was put in place. should be safe to close this one out.
