### ISSUE TITLE
Sphere trace returns wrong hit position.

### ISSUE THREAD

**Issue by osmanlodzero** [Facepunch/sbox-issues#4586]
### Describe the bug

When doing a sphere trace, the TraceResult.HitPosition returns the wrong position. It seems it's returning the end position of the sphere, not the hit position on the surface.

### To Reproduce

1. Open a scene that has some geometry to collide against.
2. Create an empty object.
3. Add a brand new component to test out traces.
4. Try the following code:

```
	protected override void OnUpdate()
	{	
		Vector3 start = Transform.Position;
		Vector3 end = start + Vector3.Down * Distance;
		var traceResult = Scene.Trace.Sphere(Radius, start, end).Run();

		/* Draw end position of sphere */
		Gizmo.Draw.IgnoreDepth = true;
		Gizmo.Draw.Color = Color.White.WithAlpha( 0.1f );
		Gizmo.Draw.LineSphere(traceResult.EndPosition, Radius );

		/* If there's a hit, draw the hit position */
		if (traceResult.Hit)
		{
			Gizmo.Draw.Color = Color.Green;
			Gizmo.Draw.SolidSphere( traceResult.HitPosition, 2.0f );

		}
	}
```

### Expected behavior

When moving the sphere around ( so not only towards the ground, but also against walls ) the hit position should return the actual position on the surface, not the center of the end position.

### Media/Files

Green sphere is the returned hit position. It should be flush on the ground.
<img width="470" alt="image" src="https://github.com/Facepunch/sbox-issues/assets/35051017/2a825465-d7b2-41dc-a4da-f9885efcf130">

**Comment by aylaylay** [comment]
This should be fixed now.

https://github.com/Facepunch/sbox-issues/assets/1667289/28f9395f-cd25-4ffe-b291-1df124a4762a

**Comment by osmanlodzero** [comment]
Nice! That looks great. I tried the latest build just now but it was still wrong, I’m assuming it’s still pending? 

Also, I noticed the hit normal returned was wrong sometimes, but I will make a new issue if I can confirm it with your new fixes. Much appreciated!

**Comment by aylaylay** [comment]
Can you show it not working? Repro?

**Comment by osmanlodzero** [comment]
Ok so I did some tests. It seems to work fine with scene objects, but not with map instaces. So the repro would be to try and load any map. In my test I used flat grass. In the video below you can see how as soon as it moves away from the gray box ( which is a scene object that I added ) and hits the map instance it shows the wrong hit position:


https://github.com/Facepunch/sbox-issues/assets/35051017/33442bb0-7e3d-4bb2-9fdb-e16a0aa07874

Hope that's helpful!

**Comment by aylaylay** [comment]
Should be fixed now

**Comment by osmanlodzero** [comment]
It works! But still has some other issues, I'll post them below:

1. When you do a sphere trace but start and end position of the trace is the same location, the normals returned don't make sense. In the video below I start with a trace of like 40 units, then 20 units, then 0, as you can see the normal returned for 0 is odd.

https://github.com/Facepunch/sbox-issues/assets/35051017/ea30a120-5f5b-469f-9fcd-870a401676c7

2. Odd normal behavior when moving trace around on a flat wall ( double checked, fully flat ). In the video below I have made the trace not 0.0 to avoid the issue above, it's set at like 2.0. The trace works fine on the floor and even on the wall, but as you move the trace around ( on a flat wall ) you get differing normals returned.


https://github.com/Facepunch/sbox-issues/assets/35051017/56dcef38-a5ec-4dcf-9d9a-8abf355248b0

Thanks!

**Comment by osmanlodzero** [comment]
So I did more tests in my actual use-case ( I want to sphere test a slightly larger radius sphere than the pawn sphere, so I can use it for fancy wall-jumps etc. This is all ported from UE4 ). While doing so I noticed some very inconsistent normals even when on the floor. When viewed with the physics debug it perhaps gives a better idea of what's going on. Video below:


https://github.com/Facepunch/sbox-issues/assets/35051017/7f5caff8-a1f6-43b6-bde7-801601f490d3

**Comment by aylaylay** [comment]
I wouldn't expect a trace with no delta to work, any detection is going to start in solid.

**Comment by aylaylay** [comment]
All of these issues look like because you're trying to start a trace inside a solid

**Comment by osmanlodzero** [comment]
The traces do start in solids, perhaps for reference footage from how Unreal handles it ( porting an old project to learn S&Box, so if there's a better way of doing things, I'm all ears!)

As you can see, I do a much larger sphere test to detect walls/floors/edges. Unreal ( PhysX in this case ) returns the following succesfully:

- Location: a point in space where you can put the swept shape where it would not be penetrating
- Impact Point:  the position on the surface that was hit
- Impact Normal: the actual surface normal of the object that was hit
- Normal: for a sphere this is a normal pointing to the center of the sphere ( for a line its the same as impact normal )

https://github.com/Facepunch/sbox-issues/assets/35051017/383f019a-5659-4c90-bcc5-ba65375bc423

I am looking for the equivelant of the normal that I'm getting in this video, I use it for all kinds of edge-jump boost type of stuff. The ball itself does not always have collision ( does for most of the time ) so I can't rely on actual collision information unfortunately.

Hope that's useful!

**Comment by aylaylay** [comment]
If unreal handles sphere traces starting in solid then we should too. I just don't know what the timeframe on that will be, it's not an easy thing to get right.

**Comment by osmanlodzero** [comment]
Totally understand! For this specific project I'll try some hacky methods for now. Thanks for taking a look :)

**Comment by MD485** [comment]
Could you provide more information, like sample code, an image, a video?

**Comment by kekobka** [comment]
```cs
	protected override void OnUpdate()
	{
		Vector3 start = Transform.Position;
		Vector3 end = start + Vector3.Down * 12;

		var traceResult = Scene.Trace.Sphere( 32, start, end ).Run();

		/* Draw end position of sphere */
		Gizmo.Draw.IgnoreDepth = true;
		Gizmo.Draw.Color = Color.Red;
		Gizmo.Draw.LineSphere( traceResult.EndPosition, 32 );

		/* If there's a hit, draw the hit position */
		if ( traceResult.Hit )
		{
			Gizmo.Draw.Color = Color.Green;
			Gizmo.Draw.SolidSphere( traceResult.HitPosition, 2.0f );

		}
	}
```

https://github.com/user-attachments/assets/878d976e-8e5f-49fb-be29-2396874ffb52

**Comment by aylaylay** [comment]
hit position for sphere casts should work again
