### ISSUE TITLE
Relative font sizes (%, em) don't use their parent, rem does not use root

### ISSUE THREAD

**Issue by MrBrax** [Facepunch/sbox-issues#5411]
### Describe the bug

Font sizes never seem to be relative to their parent, which forces hardcoding of font sizes.

### To Reproduce

1. Make a root div with font size 100px
2. Make a child div with font size 1em (this should be identical to the root font size, but it's not)
3. Make a child div with the font size 100% (this should be identical to the root font size, but it's not)

### Expected behavior

Font sizes should cascade

### Media/Files

![1714036610519](https://github.com/Facepunch/sbox-issues/assets/1517911/d0fe09a7-9860-48a9-9bf0-67407a9bdc58)

![1714036599257](https://github.com/Facepunch/sbox-issues/assets/1517911/28f91823-771d-44c7-9180-fd60df4e2ad7)

**Comment by xezno** [comment]
I think I fixed this now

**Comment by MrBrax** [comment]
![Image](https://github.com/user-attachments/assets/79009a3f-a6d5-40a1-a090-d589f954ca9e)


![Image](https://github.com/user-attachments/assets/b26ee662-9264-434f-b54f-19be666113e6)

i don't believe this is working still?

**Comment by MrBrax** [comment]
@xezno any update on this? it's still not working properly with at least parent sizes

**Comment by MrBrax** [comment]
bump
