### ISSUE TITLE
`GetAttachment` wrong position at first frame

### ISSUE THREAD

**Issue by PolSpock** [Facepunch/sbox-issues#5493]
### Describe the bug

Hi,

Since [this commit](https://discord.com/channels/833983068468936704/835035328779518023/1237836486997708881), i guess cause i didn't have this issue before,
Even if the recent [garry's attempt fix](https://discord.com/channels/833983068468936704/835035328779518023/1238460798074884106) hasn't worked

it looks like the `GetAttachment` position is now incorrect during the first tick :

![image](https://github.com/Facepunch/sbox-issues/assets/5229571/b5c494ed-b91e-41d6-bd5d-905a34de495d)
![image](https://github.com/Facepunch/sbox-issues/assets/5229571/67dfd7f3-2095-4073-a97f-a437c436a602)

### To Reproduce

1) Create `GameObject` parented to the `head` bone :
```
var goHat = new GameObject();
goHat.SetParent( bodySkinnedModelRenderer.GetBoneObject( bodySkinnedModelRenderer.Model.Bones.AllBones.Where( x => x.Name.Equals( "head" ) ).FirstOrDefault() ));
goHat.Components.Create<MyAttachment>();
```
2) Create `MyAttachment` Component:
```
public class MyAttachment : Component
{
	[Property] public SkinnedModelRenderer SkinnedModelRenderer { get; set; }

	public SkinnedModelRenderer GetPlayermodel()
	{
		return GameObject.Components.GetInAncestors<SkinnedModelRenderer>();
	}

	protected override void OnStart()
	{
		base.OnStart();

		SkinnedModelRenderer ??= GameObject.Components.GetOrCreate<SkinnedModelRenderer>();

		var model = Cloud.Model( "darg/santahatprop" );
		SkinnedModelRenderer.Model = model;

		Transform.Position = GetPlayermodel().GetAttachment( "hat" ).Value.Position;
		Transform.Rotation = GetPlayermodel().GetAttachment( "hat" ).Value.Rotation;

	}

	protected override void OnUpdate()
	{
		base.OnUpdate();

		// TOGGLE COMMENT / UNCOMMENT
		//Transform.Position = GetPlayermodel().GetAttachment( "hat" ).Value.Position;
		//Transform.Rotation = GetPlayermodel().GetAttachment( "hat" ).Value.Rotation;
	}
}
```

3) See bug `OnStart`:

https://github.com/Facepunch/sbox-issues/assets/5229571/f58d636b-9a6b-4205-8238-9625e87e2af6

### Expected behavior

Always getting the correct position of the `GetAttachment()`

### Additional context

BuildId : 14327656

**Comment by PolSpock** [comment]
I just retried and still not working for me :

Here's my complete reproduction steps :

1) Download https://github.com/Facepunch/sbox-scenestaging
2) Edit `GameNetworkManager.cs` (i hate prefab) with :
```
public sealed class GameNetworkManager : Component, Component.INetworkListener
{
	[Property] public GameObject PlayerPrefab { get; set; }
	[Property] public GameObject SpawnPoint { get; set; }

	public void OnActive( Connection channel )
	{
		Log.Info( "OnActive" );
		var player = new GameObject();
		player.Components.Create<NetworkTest>();

		var body = new GameObject();
		body.SetParent( player );

		var bodySkinnedModelRenderer = body.Components.Create<SkinnedModelRenderer>();
		bodySkinnedModelRenderer.Model = Model.Load( "models/citizen/citizen.vmdl" );
		bodySkinnedModelRenderer.CreateBoneObjects = true;

		var characterController = player.Components.Create<CharacterController>();
		var playerController = player.Components.Create<PlayerController>();
		playerController.Body = body;

		var citizenAnimationHelper = player.Components.Create<CitizenAnimationHelper>();
		citizenAnimationHelper.Target = bodySkinnedModelRenderer;

		var goHat = new GameObject();
		goHat.SetParent( bodySkinnedModelRenderer.GetBoneObject( bodySkinnedModelRenderer.Model.Bones.AllBones.Where( x => x.Name.Equals( "head" ) ).FirstOrDefault() ));
		goHat.Components.Create<MyAttachment>();

		playerController.AnimationHelper = citizenAnimationHelper;

		player.NetworkSpawn( channel );
	}
}
```
3) Create `MyAttachment.cs`:
```
	public class MyAttachment : Component
	{
		[Property] public SkinnedModelRenderer SkinnedModelRenderer { get; set; }

		public SkinnedModelRenderer GetPlayermodel()
		{
			return GameObject.Components.GetInAncestors<SkinnedModelRenderer>();
		}

		protected override void OnStart()
		{
			base.OnStart();

			SkinnedModelRenderer ??= GameObject.Components.GetOrCreate<SkinnedModelRenderer>();

			var model = Cloud.Model( "darg/santahatprop" );
			SkinnedModelRenderer.Model = model;

			Transform.Position = GetPlayermodel().GetAttachment( "hat" ).Value.Position;
			Transform.Rotation = GetPlayermodel().GetAttachment( "hat" ).Value.Rotation;

		}

		protected override void OnUpdate()
		{
			base.OnUpdate();

			// TOGGLE COMMENT / UNCOMMENT
			//Transform.Position = GetPlayermodel().GetAttachment( "hat" ).Value.Position;
			//Transform.Rotation = GetPlayermodel().GetAttachment( "hat" ).Value.Rotation;
		}
	}
```
4) Start `networking.scene`:
![image](https://github.com/Facepunch/sbox-issues/assets/5229571/983f7552-b152-4d39-83ca-4196ceec22c3)

**Comment by garrynewman** [comment]
I just committed something that might fix this one

**Comment by PolSpock** [comment]
Nop still does not work with the reproduction steps i mentioned

i used this logic since the beginning, does something need to be changed?

**Comment by PolSpock** [comment]
Hi, this issue is still present and quite frustrating since it's a **regression**.
![attachmentissue](https://github.com/Facepunch/sbox-issues/assets/5229571/30c41bd6-0e7a-4d22-a42b-5ca57460d175)

Here's another video of the issue:
https://github.com/Facepunch/sbox-issues/assets/5229571/01c45c6c-a9d9-40c2-8dc8-c046d15fe0a7

To reproduce it :

1) Download https://github.com/Facepunch/sbox-scenestaging
2) Edit `GameNetworkManager.cs` (i hate prefab) with :
```
public sealed class GameNetworkManager : Component, Component.INetworkListener
{
	public async void OnActive( Connection channel )
	{
		Log.Info( "OnActive" );
		var player = new GameObject();
		player.Tags.Add( "player" );
		var networkTest = player.Components.Create<NetworkTest>();

		var body = new GameObject();
		body.Name = "Body";
		body.SetParent( player );

		var bodySkinnedModelRenderer = body.Components.Create<SkinnedModelRenderer>();
		bodySkinnedModelRenderer.Model = Model.Load( "models/citizen/citizen.vmdl" );
		bodySkinnedModelRenderer.CreateBoneObjects = true;

		networkTest.PlayerModel = bodySkinnedModelRenderer;

		var characterController = player.Components.Create<CharacterController>();
		characterController.UseCollisionRules = true;
		var playerController = player.Components.Create<PlayerController>();
		playerController.Body = body;

		var citizenAnimationHelper = player.Components.Create<CitizenAnimationHelper>();
		citizenAnimationHelper.Target = bodySkinnedModelRenderer;

		playerController.AnimationHelper = citizenAnimationHelper;

		player.NetworkSpawn( channel );

		Log.Info( "Before + " + bodySkinnedModelRenderer.GetBoneObject( bodySkinnedModelRenderer.Model.Bones.AllBones.Where( x => x.Name.Equals( "head" ) ).FirstOrDefault() ).Transform.Position );
		var goHat = new GameObject();
		goHat.SetParent( bodySkinnedModelRenderer.GetBoneObject( bodySkinnedModelRenderer.Model.Bones.AllBones.Where( x => x.Name.Equals( "head" ) ).FirstOrDefault() ), true );
		goHat.Components.Create<MyAttachment>();

		goHat.Transform.Position = bodySkinnedModelRenderer.GetAttachment( "hat" ).Value.Position;
		goHat.Transform.Rotation = bodySkinnedModelRenderer.GetAttachment( "hat" ).Value.Rotation;

		await GameTask.DelaySeconds( 3f );

		Log.Info( "After + " + bodySkinnedModelRenderer.GetBoneObject( bodySkinnedModelRenderer.Model.Bones.AllBones.Where( x => x.Name.Equals( "head" ) ).FirstOrDefault() ).Transform.Position );

		goHat.Transform.Position = bodySkinnedModelRenderer.GetAttachment( "hat" ).Value.Position;
		goHat.Transform.Rotation = bodySkinnedModelRenderer.GetAttachment( "hat" ).Value.Rotation;

	}
}
```
3) Create `MyAttachment.cs`:
```
public class MyAttachment : Component
{
	[Property] public SkinnedModelRenderer SkinnedModelRenderer { get; set; }

	protected override void OnAwake()
	{
		base.OnStart();

		SkinnedModelRenderer ??= GameObject.Components.GetOrCreate<SkinnedModelRenderer>();

		var model = Cloud.Model( "darg/santahatprop" );
		SkinnedModelRenderer.Model = model;
	}
}
```
4) Start `networking.scene`

**Comment by aylaylay** [comment]
This should be fixed, this was what was happening:

- CreateBoneObjects created bone objects but didn't set their transforms until next animation update
- Because you parent the hat to one of these bones, setting the transform on it would set their localspace transforms as worldspace because the parent transform hasn't been set yet
- GetAttachment may have been incorrect too but that should be fixed now also
