### ISSUE TITLE
SliderControl styling appears incorrectly after Yoga 3 update

### ISSUE THREAD

**Issue by DrewBritt** [Facepunch/sbox-issues#5688]
### Describe the bug

The base library SliderControl UI panel has styling that appears incorrectly after the update to Yoga. This is because it has a few CSS classes defaulting to ```position: static```, which behaved as ```position: relative``` before, and the styling needs relative in these places.

Particularly, placing ```position: relative``` in the ```.slidercontrol > .inner > .track``` and ```... > .track > .thumb``` classes fixes the issue.

### To Reproduce

1. Open s&box player
2. Go to Settings > Input
3. Observe thicc sliders

### Expected behavior

The sliders shouldn't be thicc.

### Media/Files

![image](https://github.com/Facepunch/sbox-issues/assets/43252311/d1828e00-cb5b-4c38-97a8-6f413965f601)

**Comment by TiO2EvoLve** [comment]
It can be fixed by modifying the height
`height:8px`

**Comment by TiO2EvoLve** [comment]
<img width="951" alt="PixPin_2024-06-20_09-45-45" src="https://github.com/Facepunch/sbox-issues/assets/49835162/5168e657-b03f-455c-bd74-4d0071de2d27">
The component display does have a bug though

**Comment by DrewBritt** [comment]
These are fixed if you apply the fixes I listed in the issue.

**Comment by PolSpock** [comment]
Hi, i'm still having the issue :
Just add this somewhere :
`<SliderControl style="width: 100%;" Value:bind=@MyFloat Min=@(0) Max=@(10) Step=@(1) />`

With : `public float MyFloat { get; set; } = 1.0f;`

![image](https://github.com/user-attachments/assets/b5b98021-066c-476e-a1e7-6fe03723ec26)
