### ISSUE TITLE
FGD: color255 doesn't translate to Color/Color32 in C#

### ISSUE THREAD

**Issue by DevulTj** [Facepunch/sbox-issues#573]
**Describe the bug**

C#
```csharp
	public class BaseItemInfo
	{
		// Data from baseitem.asset
		public string Name { get; set; }
		public string Description { get; set; }
		public string Icon { get; set; }
		public string ModelPath { get; set; }
		public Color Color { get; set; }
	}

	[Library( "baseitem", Description = "An item" )]
	public class BaseItemAsset : Asset
        {
		public BaseItemInfo Data { get; set; }
        }
```

FGD
```
@struct = BaseItemInfo :
[
	Name(string) : "Name" : "Item Name"
	Description(string) : "Description" : "This is my item."
	Icon(string) : "Icon" : ""
	ModelPath(string) : "Model Path" : ""
	Color(color255) : "Color" : "0 0 0"
]

@BaseClass = baseitem : "An item"
[
	Data(struct:BaseItemInfo) : "Base Item Info"
]
```

Error
![sbox_r143dYiz9N](https://user-images.githubusercontent.com/22372616/128013554-8c511a6d-0b63-48ed-9785-289ca164890e.png)

**Comment by aylaylay** [comment]
Has this been fixed at some point? I can't replicate it

**Comment by DevulTj** [comment]
I'll give it a test today

**Comment by DevulTj** [comment]
Still getting it

```		Error when deserializing Items/Food/box.baseitem_c (The JSON value could not be converted to Color. Path: $.Data.Color | LineNumber: 7 | BytePositionInLine: 3.)```

It happens only when the asset is being loaded

**Comment by robotboy655** [comment]
This should be fixed, see also https://github.com/Facepunch/sbox-issues/issues/928
