### ISSUE TITLE
ShaderGraph - Branch node quietly changes to an attribute when re-opening older shadergraphs

### ISSUE THREAD

**Issue by Gmod4phun** [Facepunch/sbox-issues#5822]
### Describe the bug

Having an older material with an older shader created in shadergraph, I noticed recently that it did not work correctly once I recompiled the shader after the reverse-z  update. Found out that the Branch node is now by default an Attribute, and not an UI option. This is probably a thing since IsAttribute was added to the Branch node in https://github.com/Facepunch/sbox-issues/issues/5475 

This breaks older materials that relied on it being a UI option in the material editor. I noticed it when my material was no longer grayscale because of the branch node quietly changing to attribute.

![image](https://github.com/user-attachments/assets/861ed5bb-4464-4c8f-a89b-7c025c065c13)

### To Reproduce

1. Have a shadergraph that was created before the Branch node had the ability to be an attribute
2. Open the shadergraph, and re-save it
3. See that the Branch is now an Attribute
4. Materials that used the old shader can now not work properly

### Expected behavior

Most likely have the older shadergraphs (the ones that did not have IsAttribute set on the Branch node in the .shdrgrph) set the IsAttribute to false by default.

**Comment by DevulTj** [comment]
I have a feeling this is related to a JSON deserialization issue we're having where it won't deserialize to the default value of the property, it'll use the default value of the type.

**Comment by Gmod4phun** [comment]
Unless I'm missing something, the default for bool should be false, but it is true, so I suspect it does indeed use the default of the property, since when you add a fresh Branch node in the shadergraph, it will have IsAttribute checked.

**Comment by CarsonKompon** [comment]
This should be fixed now, can you confirm on your end?

**Comment by Gmod4phun** [comment]
I cant tell for sure because it seems my shadergraph shaders are completely fucked (feels like some nodes might be disconnected, because I dont remember doing that myself), so I will have to get back to you on this one.

**Comment by Gmod4phun** [comment]
Regarding the Branch node issue, that one sadly seems to not be fixed. Opening an older shadergraph which doesnt have the IsAttribute still results in it being set to true by default. (can be seen in the video at the 16 second mark).

https://www.youtube.com/watch?v=cFRkj1bQLFw

The video also shows the issue of disconnected nodes. It seems like outputs of all my Combine nodes are disconnected from where they were connected before (not sure when this broke, if today, or it happened longer ago). If that wont be fixed by tomorrow, I will probably do some more investigating and create a separate issue for that (have to go now).

Here are the older shadergraph files, if it helps: 

[shaders_july_8_2024.zip](https://github.com/user-attachments/files/18430953/shaders_july_8_2024.zip)

**Comment by CarsonKompon** [comment]
Likely to do with my changes from today, your files will help me a bunch in investigating tomorrow :)

**Comment by CarsonKompon** [comment]
I have fixed the issue with the broken connections in those graphs, and on my end I'm still able to set IsAttribute to false just fine without it changing itself back. Can you confirm?

**Comment by Gmod4phun** [comment]
Node connections seem to be fine now, thanks :). The Branch node, still not. But just in case there is a misunderstanding, the issue is that when the branch node in an old saved shadergraph does not have the IsAttribute property, it will get set to True once you open the shadergraph in the editor. You can then set it to false and it stays that way, there's no problem with that. The only problem is that it will be set to true by default.

Admittedly, its not really a big deal, you can just open it and go set the IsAttribute to false, but unless people know that this happened, opening older shadergraphs will silently switch to an attribute and thus change behaviour.
