### ISSUE TITLE
Using Block Tool in Scene crashes the game

### ISSUE THREAD

**Issue by DiamondSander** [Facepunch/sbox-issues#5949]
### Describe the bug

I have a scene where I'm trying to create geometry using the block tool. When I hit enter to confirm and place the geometry, this editor crashes completely.

### To Reproduce

Click on Block Tool.

Drag out a cube

Hit Enter

Editor Crashes

### Expected behavior

Intended behavior is to create geometry i can further edit

### Additional context

I am running on windows 11, with a 13th gen i5 intel core. the GPU IS Nvidia Geforce RTX 4050

**Comment by aylaylay** [comment]
Fixed

**Comment by DiamondSander** [comment]
Hey Aylaylay, im still experiencing this issue, I'm going to show a video here from when I launch the project from when I use the block tool to when it crashes at the end when I hate enter.

https://github.com/user-attachments/assets/36d2b21d-58c3-4903-b8ea-44433d362a4a

**Comment by aylaylay** [comment]
You have to update your game on steam to get updates

**Comment by DiamondSander** [comment]
thank you its fixed
