### ISSUE TITLE
[Vulkan] Editor crash everytime

### ISSUE THREAD

**Issue by bub-bl** [Facepunch/sbox-issues#5983]
### Describe the bug

WHen i launch the editor, the editor crash after few seconds or when i move the scene tab or the game tab

### To Reproduce

- Launch the editor
- Move some tabs side by side like the game tab or the scene tab

### Expected behavior

The editor will dont crash

### Media/Files

[Log.log](https://github.com/user-attachments/files/16405400/Log.log)

https://github.com/user-attachments/assets/42093930-5c22-4c8d-ac5e-330df42c37d1

### Additional context

Windows 11
Nvidia 2060 SUPER (Latest drivers update)

**Comment by handsomematt** [comment]
Has this started happening recently? Can you run vulkaninfo and provide results https://nvidia.custhelp.com/app/answers/detail/a_id/5429/~/running-vulkan-info

**Comment by bub-bl** [comment]
> Has this started happening recently? Can you run vulkaninfo and provide results https://nvidia.custhelp.com/app/answers/detail/a_id/5429/~/running-vulkan-info

I've had this problem since ~10pm, an update was released, I restarted the editor and since then I still have the problem. 

This is the result:
[infos.txt](https://github.com/user-attachments/files/16405590/infos.txt)

**Comment by handsomematt** [comment]
I don't think we've pushed anything rendering related tonight.. It's been fine yesterday and before?

Only thing I can ask you to try now is uninstalling Overwolf as it fucks with a lot of shit.

**Comment by bub-bl** [comment]
I still have the same problem after completely uninstalling Overwolf + Restarting the computer

I've never had any problems since I've been using the editor, I haven't done anything special, I haven't installed anything on my computer. The problem occurred all of a sudden for no apparent reason.

**Comment by bub-bl** [comment]
I have created a new project and i dont have this problem with them. I just will disable all my gameobject and re enable it to see whats cause this issue

**Comment by bub-bl** [comment]
The problem seem to be caused by The `HighlightOutline` component. When i enable it, the editor crash instantly. The game doesnt crash i disable it

**Comment by bub-bl** [comment]
Ok, I think I've found the real problem...
I've created a material with a render target that displays the camera on a plane. I'm pretty sure I must be exceeding some rendering limit or something.

Other than that, I don't know what it could come from.
https://github.com/user-attachments/assets/0c67c580-9727-440b-bc03-b972365ccaf5

**Comment by handsomematt** [comment]
Awesome, thanks for the thorough diagnosis. I'll take a look.

**Comment by bub-bl** [comment]
> Awesome, thanks for the thorough diagnosis. I'll take a look.

You should take a look at `Camera.RenderToTexture`, the problem occurs exactly on this line

https://github.com/user-attachments/assets/79c80852-e948-40f4-bf92-efcea02b803f

**Comment by bub-bl** [comment]
I have set the texture resolution to 512x512. using a power of 2 resolution seem to "decrease" the crash frequency

Also, i have let the game running a long time, the editor crash after ~15 minutes without touching anything.
```
2024/07/29 14:15:19.8680	[engine/Engine] C:\build\_work\sbox\sbox\src\rendersystem\texturebase.cpp(3519):ResourceHandleToData(  ) failed! Falling back to error texture!
```

**Comment by handsomematt** [comment]
Do you think you could do a minimal .sbproj reproduction of this? My time is minimal currently but I'd love to get this fixed for you asap

**Comment by bub-bl** [comment]
I've tried a whole bunch of things in a new project (in an empty scene), the problem doesn't seem to be happening. I think it must be an accumulation of a lot of things. Graphics memory overflow or something like that. In my other project, the problem always occurs when I do something very specific, but doesn't seem to happen in the new project when reproducing the same thing.

For the moment, I've found a solution that greatly reduces the frequency of crashes, checking my entire project and removing all errors linked to missing textures, non-compiled materials etc. This seems to alleviate my problem. I think I'm an isolated case and that the problem must surely occur in a very specific case depending on the hardware configuration used.

**Comment by handsomematt** [comment]
There was a memory overflow with cubemaps, may have been triggering this one. See if it's made a difference I suppose.

**Comment by bub-bl** [comment]
The problem is not solved on my side, but it only trigger when i use a resolution with a non power of 2. So for now i use this hack to avoid this issue

**Comment by handsomematt** [comment]
Can you add me to your git repo and tell me what makes it crash

**Comment by bub-bl** [comment]
I have finally found the issue !

The problem is caused only when no gpu memory is available to generate the texture.
But that is not the real problem. The real problem is related to the wrong gpu memory cleaning.

When you load your scene, some textures are loaded in the GPU. But these textures are not cleaned when the scene is stopped. That cause a gpu memory overflow.

If you run and stop a lot of times your scene, you can see a lot of not unloaded and duplicated textures in GPU Resident Texture window.

When i load my scene for the first time, i have ~300 textures loaded. After some start / stop scene action, i got ~1100 textures loaded in the GPU without doing nothing, just start / stop the scene. And you can see in the video bellow, i have the same duplicated multiple times texture and these textures are not cleaned.

https://github.com/user-attachments/assets/fcfe3c23-36d0-4031-96ed-9ee184b06b3f

**Comment by handsomematt** [comment]
Awesome analysis! Should be able to fix it from that.
