### ISSUE TITLE
Exception when getting API: "Backend Error - returned InteralServerError" - Can no longer get any stats

### ISSUE THREAD

**Issue by Coomzy** [Facepunch/sbox-issues#6261]
### Describe the bug

Every single time I load up the project (both editor and packaged) or try and get any stat from the backend I get the same error twice (local and global) and it fails to get the stat.

Error: `Generic Exception when getting API "https://services.facepunch.com/sbox/package/stats/coomzy.broken_stats_example/"`

Leaderboards seem to still work although while making the example project for this, the 'non broken stat' leaderboard now doesn't work, this could be a different issue though. 

Error: `Couldn't deserialize [Sandbox.Api+LeaderboardResponse](arg:0) [https://services.facepunch.com/sbox/package/leaderboard/coomzy.broken_stats_example/non-broken-example/u/76561198035887310/global?take=10]`

I'm pretty sure I know what caused it and that was incrementing the stat by double.MaxValue, it might need to be done more than once to make it overflow. I know it was dumb of me but I had a default time set to maxValue and accidently uploaded it, ever since then it's been broken.

### To Reproduce

1. Create New Project
2. Publish Project
3. Enable Stats feature
4. Create new stat
5. Increment stat by double.MaxValue (might need to do this twice to make it overflow not sure)
6. Reload project or try and get a stat

Alternatively I made an example project: https://github.com/Coomzy/Sandbox-Broken-Stats-Example

### Expected behavior

I expect setting the stat in a bad state to either not be acceptable, give a better error and not break getting the other stats.

I know the stats/leaderboards stuff is WIP, but if being able to delete stats was added, I could probably fix it myself

### Media/Files

**[Errors]**
![image](https://github.com/user-attachments/assets/e1662733-bd79-4614-983d-8168c5d3cce1)
![image](https://github.com/user-attachments/assets/fa14bfe4-2b1b-456a-aa47-876c86bcf701)

**[Backend]**
![image](https://github.com/user-attachments/assets/42295447-4cf7-46ee-a7ff-4243943a9999)
![image](https://github.com/user-attachments/assets/09283e32-df14-4d2b-a0ba-26c8754d35c3)

**[Leaderboard Error]**
![image](https://github.com/user-attachments/assets/2b31a38e-ba0b-4e28-8a49-aff422f23930)
![image](https://github.com/user-attachments/assets/8ffe5a62-98ef-4afc-8c58-797d3d7af479)

### Additional context

[Example]
Backend: https://sbox.game/coomzy/broken_stats_example/stats/v/example/explore
GitHub Project: https://github.com/Coomzy/Sandbox-Broken-Stats-Example

[Game Jam Project]
I'd also like to mention I have this issue on my game jam project, so I can't pull any stats without getting this error.
I was wondering if it'd be possible to delete the stat from the backend manually, since I have no way to do so?
Game Jam Project: https://sbox.game/coomzy/shootordontshoot/stats/v/level-original/

**Comment by garrynewman** [comment]
I fixed the errors on this, but I need to fix the root cause, will do that tomorrow.

**Comment by Coomzy** [comment]
I can confirm that I see the stats screen again. However, when I use the raw view, my local stats still show a very large number. I can live with that, though.
