### ISSUE TITLE
Multiple scene cameras break shadows

### ISSUE THREAD

**Issue by dch-GH** [Facepunch/sbox-issues#6343]
### Describe the bug

Having another scene camera present in a scene breaks certain shadows. Maybe only shadows from dynamic (non-hammer-map) scene objects?

### To Reproduce

1. Have a main camera at priority 16.
2. Have a secondary camera at any lower priority.
3. Shadows break

### Expected behavior

Multiple scene cameras functioning normally. There is also another issue with `RenderEffect` hooks on 1 camera, disrupting or breaking `RenderEffect` hooks on camera 2 but I'll make another issue for that.

### Media/Files

https://github.com/user-attachments/assets/0617a179-9a0b-4df5-850b-8c6475848c53

**Comment by samzanemesis** [comment]
We have a shadow cache system to avoid shadows being rendered more than needed, going with that is a system to render shadows with far resolution, the cache system could have a bias for multiple cameras to fix it

**Comment by samzanemesis** [comment]
That was GPU culling, shadow cache was not breaking it, should work now

**Comment by dch-GH** [comment]
> That was GPU culling, shadow cache was not breaking it, should work now

Still happening on [#13bd34](https://commits.facepunch.com/495231)

https://github.com/user-attachments/assets/6e60fe88-f729-429d-8dcc-6c7b635e14dd

For more information: the second camera is pointed directly down at the player position (right below Camera 1) and is 
 set to orthographic.

**Comment by dch-GH** [comment]
Realized this was logging as well:

```
 04:52:40   engine/RenderSystem returning error texture resource for "" in CTextureManagerVK::GetTextureResource
 04:52:40   engine/Engine C:\build\_work\sbox\sbox\src\rendersystem\texturebase.cpp(3519):ResourceHandleToData( __cache_color_-810264942.vtex ) failed! Falling back to error texture!
 04:52:40   engine/RenderSystem returning error texture resource for "" in CTextureManagerVK::GetTextureResource
 04:52:40   engine/Engine C:\build\_work\sbox\sbox\src\rendersystem\texturebase.cpp(3519):ResourceHandleToData( __cache_color_54536087.vtex ) failed! Falling back to error texture!
 04:52:40   engine/RenderSystem returning error texture resource for "" in CTextureManagerVK::GetTextureResource
 04:52:40   engine/Engine C:\build\_work\sbox\sbox\src\rendersystem\texturebase.cpp(3519):ResourceHandleToData( __cache_color_54536087.vtex ) failed! Falling back to error texture!
 04:52:40   engine/RenderSystem returning error texture resource for "" in CTextureManagerVK::GetTextureResource
 04:52:40   engine/Engine C:\build\_work\sbox\sbox\src\rendersystem\texturebase.cpp(3519):ResourceHandleToData( __cache_color_54536087.vtex ) failed! Falling back to error texture!
```
Stacktrace:
![image](https://github.com/user-attachments/assets/3104d32f-75f0-41bd-92e7-dde82dd1114e)

**Comment by Nanou-Lapin** [comment]
I have the same problem : 

2024/09/06 08:16:52.0791	[engine/ToolsStallMonitor] Stall detected.	
2024/09/06 08:16:53.7313	[engine/RenderSystem] returning error texture resource for "" in CTextureManagerVK::GetTextureResource	
2024/09/06 08:16:53.7313	[engine/Engine] C:\build\_work\sbox\sbox\src\rendersystem\texturebase.cpp(3519):ResourceHandleToData( unnamed.vtex ) failed! Falling back to error texture!	
2024/09/06 08:16:53.7313	[engine/RenderSystem] returning error texture resource for "" in CTextureManagerVK::GetTextureResource	
2024/09/06 08:16:53.7313	[engine/Engine] C:\build\_work\sbox\sbox\src\rendersystem\texturebase.cpp(3519):ResourceHandleToData( unnamed.vtex ) failed! Falling back to error texture!	
2024/09/06 08:16:53.7313	[engine/RenderSystem] returning error texture resource for "" in CTextureManagerVK::GetTextureResource	
2024/09/06 08:16:53.7313	[engine/Engine] C:\build\_work\sbox\sbox\src\rendersystem\texturebase.cpp(3519):ResourceHandleToData( unnamed.vtex ) failed! Falling back to error texture!	
2024/09/06 08:16:53.7313	[engine/RenderSystem] returning error texture resource for "" in CTextureManagerVK::GetTextureResource	
2024/09/06 08:16:53.7313	[engine/Engine] C:\build\_work\sbox\sbox\src\rendersystem\texturebase.cpp(3519):ResourceHandleToData( unnamed.vtex ) failed! Falling back to error texture!	
2024/09/06 08:16:53.7313	[engine/RenderSystem] returning error texture resource for "" in CTextureManagerVK::GetTextureResource	
2024/09/06 08:16:53.7313	[engine/Engine] C:\build\_work\sbox\sbox\src\rendersystem\texturebase.cpp(3519):ResourceHandleToData( unnamed.vtex ) failed! Falling back to error texture!	
2024/09/06 08:16:53.7313	[engine/RenderSystem] returning error texture resource for "" in CTextureManagerVK::GetTextureResource	
2024/09/06 08:16:53.7313	[engine/Engine] C:\build\_work\sbox\sbox\src\rendersystem\texturebase.cpp(3519):ResourceHandleToData( unnamed.vtex ) failed! Falling back to error texture!	
2024/09/06 08:16:53.7313	[engine/RenderSystem] returning error texture resource for "" in CTextureManagerVK::GetTextureResource	
2024/09/06 08:16:53.7313	[engine/Engine] C:\build\_work\sbox\sbox\src\rendersystem\texturebase.cpp(3519):ResourceHandleToData( unnamed.vtex ) failed! Falling back to error texture!	
2024/09/06 08:16:53.7313	[engine/RenderSystem] returning error texture resource for "" in CTextureManagerVK::GetTextureResource	
2024/09/06 08:16:53.7313	[engine/Engine] C:\build\_work\sbox\sbox\src\rendersystem\texturebase.cpp(3519):ResourceHandleToData( unnamed.vtex ) failed! Falling back to error texture!	
2024/09/06 08:16:53.7400	[engine/RenderSystem] returning error texture resource for "" in CTextureManagerVK::GetTextureResource	
2024/09/06 08:16:53.7400	[engine/Engine] C:\build\_work\sbox\sbox\src\rendersystem\texturebase.cpp(3519):ResourceHandleToData( unnamed.vtex ) failed! Falling back to error texture!	
2024/09/06 08:16:53.7400	[engine/RenderSystem] returning error texture resource for "" in CTextureManagerVK::GetTextureResource	
2024/09/06 08:16:53.7400	[engine/Engine] C:\build\_work\sbox\sbox\src\rendersystem\texturebase.cpp(3519):ResourceHandleToData( unnamed.vtex ) failed! Falling back to error texture!	
2024/09/06 08:16:53.7400	[engine/RenderSystem] returning error texture resource for "" in CTextureManagerVK::GetTextureResource	
2024/09/06 08:16:53.7400	[engine/Engine] C:\build\_work\sbox\sbox\src\rendersystem\texturebase.cpp(3519):ResourceHandleToData( unnamed.vtex ) failed! Falling back to error texture!	
2024/09/06 08:16:53.7400	[engine/RenderSystem] returning error texture resource for "" in CTextureManagerVK::GetTextureResource	
2024/09/06 08:16:53.7400	[engine/Engine] C:\build\_work\sbox\sbox\src\rendersystem\texturebase.cpp(3519):ResourceHandleToData( unnamed.vtex ) failed! Falling back to error texture!	
2024/09/06 08:16:53.7400	[engine/RenderSystem] returning error texture resource for "" in CTextureManagerVK::GetTextureResource	
2024/09/06 08:16:53.7400	[engine/Engine] C:\build\_work\sbox\sbox\src\rendersystem\texturebase.cpp(3519):ResourceHandleToData( unnamed.vtex ) failed! Falling back to error texture!	
2024/09/06 08:16:53.7400	[engine/RenderSystem] returning error texture resource for "" in CTextureManagerVK::GetTextureResource	
2024/09/06 08:16:53.7400	[engine/Engine] C:\build\_work\sbox\sbox\src\rendersystem\texturebase.cpp(3519):ResourceHandleToData( unnamed.vtex ) failed! Falling back to error texture!	
2024/09/06 08:16:53.7400	[engine/RenderSystem] returning error texture resource for "" in CTextureManagerVK::GetTextureResource	
2024/09/06 08:16:53.7400	[engine/Engine] C:\build\_work\sbox\sbox\src\rendersystem\texturebase.cpp(3519):ResourceHandleToData( unnamed.vtex ) failed! Falling back to error texture!	
2024/09/06 08:16:53.7400	[engine/RenderSystem] returning error texture resource for "" in CTextureManagerVK::GetTextureResource	
2024/09/06 08:16:53.7400	[engine/Engine] C:\build\_work\sbox\sbox\src\rendersystem\texturebase.cpp(3519):ResourceHandleToData( unnamed.vtex ) failed! Falling back to error texture!	
2024/09/06 08:16:53.7400	[engine/RenderSystem] returning error texture resource for "" in CTextureManagerVK::GetTextureResource	
2024/09/06 08:16:53.7400	[engine/Engine] C:\build\_work\sbox\sbox\src\rendersystem\texturebase.cpp(3519):ResourceHandleToData( unnamed.vtex ) failed! Falling back to error texture!	
2024/09/06 08:16:53.7400	[engine/RenderSystem] returning error texture resource for "" in CTextureManagerVK::GetTextureResource	
2024/09/06 08:16:53.7400	[engine/Engine] C:\build\_work\sbox\sbox\src\rendersystem\texturebase.cpp(3519):ResourceHandleToData( unnamed.vtex ) failed! Falling back to error texture!	
2024/09/06 08:16:53.7400	[engine/RenderSystem] returning error texture resource for "" in CTextureManagerVK::GetTextureResource	
2024/09/06 08:16:53.7400	[engine/Engine] C:\build\_work\sbox\sbox\src\rendersystem\texturebase.cpp(3519):ResourceHandleToData( unnamed.vtex ) failed! Falling back to error texture!	
2024/09/06 08:16:53.7400	[engine/RenderSystem] returning error texture resource for "" in CTextureManagerVK::GetTextureResource	
2024/09/06 08:16:53.7400	[engine/Engine] C:\build\_work\sbox\sbox\src\rendersystem\texturebase.cpp(3519):ResourceHandleToData( unnamed.vtex ) failed! Falling back to error texture!	
2024/09/06 08:16:53.7400	[engine/RenderSystem] returning error texture resource for "" in CTextureManagerVK::GetTextureResource	
2024/09/06 08:16:53.7400	[engine/Engine] C:\build\_work\sbox\sbox\src\rendersystem\texturebase.cpp(3519):ResourceHandleToData( unnamed.vtex ) failed! Falling back to error texture!	
2024/09/06 08:16:53.7400	[engine/RenderSystem] returning error texture resource for "" in CTextureManagerVK::GetTextureResource	
2024/09/06 08:16:53.7400	[engine/Engine] C:\build\_work\sbox\sbox\src\rendersystem\texturebase.cpp(3519):ResourceHandleToData( unnamed.vtex ) failed! Falling back to error texture!	
2024/09/06 08:16:53.7400	[engine/RenderSystem] returning error texture resource for "" in CTextureManagerVK::GetTextureResource	
2024/09/06 08:16:53.7400	[engine/Engine] C:\build\_work\sbox\sbox\src\rendersystem\texturebase.cpp(3519):ResourceHandleToData( unnamed.vtex ) failed! Falling back to error texture!	
2024/09/06 08:16:53.7560	[engine/RenderSystem] returning error texture resource for "" in CTextureManagerVK::GetTextureResource	
2024/09/06 08:16:53.7560	[engine/Engine] C:\build\_work\sbox\sbox\src\rendersystem\texturebase.cpp(3519):ResourceHandleToData( unnamed.vtex ) failed! Falling back to error texture!	
2024/09/06 08:16:53.7560	[engine/RenderSystem] returning error texture resource for "" in CTextureManagerVK::GetTextureResource	
2024/09/06 08:16:53.7560	[engine/Engine] C:\build\_work\sbox\sbox\src\rendersystem\texturebase.cpp(3519):ResourceHandleToData( unnamed.vtex ) failed! Falling back to error texture!	
2024/09/06 08:16:53.7560	[engine/RenderSystem] returning error texture resource for "" in CTextureManagerVK::GetTextureResource	
2024/09/06 08:16:53.7560	[engine/Engine] C:\build\_work\sbox\sbox\src\rendersystem\texturebase.cpp(3519):ResourceHandleToData( unnamed.vtex ) failed! Falling back to error texture!	
2024/09/06 08:16:53.7560	[engine/RenderSystem] returning error texture resource for "" in CTextureManagerVK::GetTextureResource	
2024/09/06 08:16:53.7560	[engine/Engine] C:\build\_work\sbox\sbox\src\rendersystem\texturebase.cpp(3519):ResourceHandleToData( unnamed.vtex ) failed! Falling back to error texture!	
2024/09/06 08:16:53.7560	[engine/RenderSystem] returning error texture resource for "" in CTextureManagerVK::GetTextureResource	
2024/09/06 08:16:53.7560	[engine/Engine] C:\build\_work\sbox\sbox\src\rendersystem\texturebase.cpp(3519):ResourceHandleToData( unnamed.vtex ) failed! Falling back to error texture!	
2024/09/06 08:16:53.7560	[engine/RenderSystem] returning error texture resource for "" in CTextureManagerVK::GetTextureResource	
2024/09/06 08:16:53.7560	[engine/Engine] C:\build\_work\sbox\sbox\src\rendersystem\texturebase.cpp(3519):ResourceHandleToData( unnamed.vtex ) failed! Falling back to error texture!	
2024/09/06 08:16:53.8296	[engine/RenderSystem] returning error texture resource for "" in CTextureManagerVK::GetTextureResource	
2024/09/06 08:16:53.8296	[engine/Engine] C:\build\_work\sbox\sbox\src\rendersystem\texturebase.cpp(3519):ResourceHandleToData( unnamed.vtex ) failed! Falling back to error texture!	
2024/09/06 08:16:53.8296	[engine/RenderSystem] returning error texture resource for "" in CTextureManagerVK::GetTextureResource	
2024/09/06 08:16:53.8296	[engine/Engine] C:\build\_work\sbox\sbox\src\rendersystem\texturebase.cpp(3519):ResourceHandleToData( unnamed.vtex ) failed! Falling back to error texture!	
2024/09/06 08:16:53.8296	[engine/RenderSystem] returning error texture resource for "" in CTextureManagerVK::GetTextureResource	
2024/09/06 08:16:53.8296	[engine/Engine] C:\build\_work\sbox\sbox\src\rendersystem\texturebase.cpp(3519):ResourceHandleToData( unnamed.vtex ) failed! Falling back to error texture!	
2024/09/06 08:16:53.8333	[engine/RenderSystem] returning error texture resource for "" in CTextureManagerVK::GetTextureResource	
2024/09/06 08:16:53.8333	[engine/Engine] C:\build\_work\sbox\sbox\src\rendersystem\texturebase.cpp(3519):ResourceHandleToData( unnamed.vtex ) failed! Falling back to error texture!	
2024/09/06 08:16:53.8333	[engine/RenderSystem] returning error texture resource for "" in CTextureManagerVK::GetTextureResource	
2024/09/06 08:16:53.8333	[engine/Engine] C:\build\_work\sbox\sbox\src\rendersystem\texturebase.cpp(3519):ResourceHandleToData( unnamed.vtex ) failed! Falling back to error texture!	
2024/09/06 08:16:53.8333	[engine/RenderSystem] returning error texture resource for "" in CTextureManagerVK::GetTextureResource	
2024/09/06 08:16:53.8333	[engine/Engine] C:\build\_work\sbox\sbox\src\rendersystem\texturebase.cpp(3519):ResourceHandleToData( unnamed.vtex ) failed! Falling back to error texture!	
2024/09/06 08:16:53.8333	[engine/RenderSystem] returning error texture resource for "" in CTextureManagerVK::GetTextureResource	
2024/09/06 08:16:53.8333	[engine/Engine] C:\build\_work\sbox\sbox\src\rendersystem\texturebase.cpp(3519):ResourceHandleToData( unnamed.vtex ) failed! Falling back to error texture!	
2024/09/06 08:16:53.8333	[engine/RenderSystem] returning error texture resource for "" in CTextureManagerVK::GetTextureResource	
2024/09/06 08:16:53.8333	[engine/Engine] C:\build\_work\sbox\sbox\src\rendersystem\texturebase.cpp(3519):ResourceHandleToData( unnamed.vtex ) failed! Falling back to error texture!	
2024/09/06 08:16:53.8333	[engine/RenderSystem] returning error texture resource for "" in CTextureManagerVK::GetTextureResource	
2024/09/06 08:16:53.8333	[engine/Engine] C:\build\_work\sbox\sbox\src\rendersystem\texturebase.cpp(3519):ResourceHandleToData( unnamed.vtex ) failed! Falling back to error texture!	
2024/09/06 08:16:53.8333	[engine/RenderSystem] returning error texture resource for "" in CTextureManagerVK::GetTextureResource	
2024/09/06 08:16:53.8333	[engine/Engine] C:\build\_work\sbox\sbox\src\rendersystem\texturebase.cpp(3519):ResourceHandleToData( unnamed.vtex ) failed! Falling back to error texture!	
2024/09/06 08:16:53.8333	[engine/RenderSystem] returning error texture resource for "" in CTextureManagerVK::GetTextureResource	
2024/09/06 08:16:53.8333	[engine/Engine] C:\build\_work\sbox\sbox\src\rendersystem\texturebase.cpp(3519):ResourceHandleToData( unnamed.vtex ) failed! Falling back to error texture!	
2024/09/06 08:16:53.8333	[engine/RenderSystem] returning error texture resource for "" in CTextureManagerVK::GetTextureResource	
2024/09/06 08:16:53.8333	[engine/Engine] C:\build\_work\sbox\sbox\src\rendersystem\texturebase.cpp(3519):ResourceHandleToData( unnamed.vtex ) failed! Falling back to error texture!	
2024/09/06 08:16:53.8333	[engine/RenderSystem] returning error texture resource for "" in CTextureManagerVK::GetTextureResource	
2024/09/06 08:16:53.8333	[engine/Engine] C:\build\_work\sbox\sbox\src\rendersystem\texturebase.cpp(3519):ResourceHandleToData( unnamed.vtex ) failed! Falling back to error texture!	
2024/09/06 08:16:53.8333	[engine/RenderSystem] returning error texture resource for "" in CTextureManagerVK::GetTextureResource	
2024/09/06 08:16:53.8333	[engine/Engine] C:\build\_work\sbox\sbox\src\rendersystem\texturebase.cpp(3519):ResourceHandleToData( unnamed.vtex ) failed! Falling back to error texture!	
2024/09/06 08:16:53.8333	[engine/RenderSystem] returning error texture resource for "" in CTextureManagerVK::GetTextureResource	
2024/09/06 08:16:53.8333	[engine/Engine] C:\build\_work\sbox\sbox\src\rendersystem\texturebase.cpp(3519):ResourceHandleToData( unnamed.vtex ) failed! Falling back to error texture!	
2024/09/06 08:16:53.8333	[engine/RenderSystem] returning error texture resource for "" in CTextureManagerVK::GetTextureResource	
2024/09/06 08:16:53.8333	[engine/Engine] C:\build\_work\sbox\sbox\src\rendersystem\texturebase.cpp(3519):ResourceHandleToData( unnamed.vtex ) failed! Falling back to error texture!	
2024/09/06 08:16:53.8333	[engine/RenderSystem] returning error texture resource for "" in CTextureManagerVK::GetTextureResource	
2024/09/06 08:16:53.8492	[engine/Engine] C:\build\_work\sbox\sbox\src\rendersystem\texturebase.cpp(3519):ResourceHandleToData( unnamed.vtex ) failed! Falling back to error texture!	
2024/09/06 08:16:53.8492	[engine/RenderSystem] returning error texture resource for "" in CTextureManagerVK::GetTextureResource	
2024/09/06 08:16:53.8492	[engine/Engine] C:\build\_work\sbox\sbox\src\rendersystem\texturebase.cpp(3519):ResourceHandleToData( unnamed.vtex ) failed! Falling back to error texture!	
2024/09/06 08:16:53.8492	[engine/RenderSystem] returning error texture resource for "" in CTextureManagerVK::GetTextureResource	
2024/09/06 08:16:53.8492	[engine/Engine] C:\build\_work\sbox\sbox\src\rendersystem\texturebase.cpp(3519):ResourceHandleToData( unnamed.vtex ) failed! Falling back to error texture!	
2024/09/06 08:16:53.8492	[engine/RenderSystem] returning error texture resource for "" in CTextureManagerVK::GetTextureResource	
2024/09/06 08:16:53.8492	[engine/Engine] C:\build\_work\sbox\sbox\src\rendersystem\texturebase.cpp(3519):ResourceHandleToData( unnamed.vtex ) failed! Falling back to error texture!	
2024/09/06 08:16:53.8492	[engine/RenderSystem] returning error texture resource for "" in CTextureManagerVK::GetTextureResource	
2024/09/06 08:16:53.8492	[engine/Engine] C:\build\_work\sbox\sbox\src\rendersystem\texturebase.cpp(3519):ResourceHandleToData( unnamed.vtex ) failed! Falling back to error texture!	
2024/09/06 08:16:53.8492	[engine/Engine] C:\build\_work\sbox\sbox\src\rendersystem\texturebase.cpp(3519):ResourceHandleToData( unnamed.vtex ) failed! Falling back to error texture!	
2024/09/06 08:16:53.8492	[engine/Engine] C:\build\_work\sbox\sbox\src\rendersystem\texturebase.cpp(3519):ResourceHandleToData( unnamed.vtex ) failed! Falling back to error texture!	
2024/09/06 08:16:53.8492	[engine/Engine] C:\build\_work\sbox\sbox\src\rendersystem\texturebase.cpp(3519):ResourceHandleToData( unnamed.vtex ) failed! Falling back to error texture!	
2024/09/06 08:16:53.8492	[engine/Engine] C:\build\_work\sbox\sbox\src\rendersystem\texturebase.cpp(3519):ResourceHandleToData( unnamed.vtex ) failed! Falling back to error texture!	
2024/09/06 08:16:53.8492	[engine/Engine] C:\build\_work\sbox\sbox\src\rendersystem\texturebase.cpp(3519):ResourceHandleToData( unnamed.vtex ) failed! Falling back to error texture!	
2024/09/06 08:16:53.8492	[engine/Engine] C:\build\_work\sbox\sbox\src\rendersystem\texturebase.cpp(3519):ResourceHandleToData( unnamed.vtex ) failed! Falling back to error texture!	
2024/09/06 08:16:53.8492	[engine/Engine] C:\build\_work\sbox\sbox\src\rendersystem\texturebase.cpp(3519):ResourceHandleToData( unnamed.vtex ) failed! Falling back to error texture!	
2024/09/06 08:16:53.8492	[engine/Engine] C:\build\_work\sbox\sbox\src\rendersystem\texturebase.cpp(3519):ResourceHandleToData( unnamed.vtex ) failed! Falling back to error texture!	
2024/09/06 08:16:53.8492	[engine/Engine] C:\build\_work\sbox\sbox\src\rendersystem\texturebase.cpp(3519):ResourceHandleToData( unnamed.vtex ) failed! Falling back to error texture!	
2024/09/06 08:16:53.8492	[engine/Engine] C:\build\_work\sbox\sbox\src\rendersystem\texturebase.cpp(3519):ResourceHandleToData( unnamed.vtex ) failed! Falling back to error texture!	
2024/09/06 08:16:53.8492	[engine/Engine] C:\build\_work\sbox\sbox\src\rendersystem\texturebase.cpp(3519):ResourceHandleToData( unnamed.vtex ) failed! Falling back to error texture!	
2024/09/06 08:16:53.8492	[engine/Engine] C:\build\_work\sbox\sbox\src\rendersystem\texturebase.cpp(3519):ResourceHandleToData( unnamed.vtex ) failed! Falling back to error texture!	
2024/09/06 08:16:53.8492	[engine/Engine] C:\build\_work\sbox\sbox\src\rendersystem\texturebase.cpp(3519):ResourceHandleToData( unnamed.vtex ) failed! Falling back to error texture!	
2024/09/06 08:16:53.8492	[engine/Engine] C:\build\_work\sbox\sbox\src\rendersystem\texturebase.cpp(3519):ResourceHandleToData( unnamed.vtex ) failed! Falling back to error texture!	
2024/09/06 08:16:53.8492	[engine/Engine] C:\build\_work\sbox\sbox\src\rendersystem\texturebase.cpp(3519):ResourceHandleToData( unnamed.vtex ) failed! Falling back to error texture!	
2024/09/06 08:16:53.8648	[engine/Engine] C:\build\_work\sbox\sbox\src\rendersystem\texturebase.cpp(3519):ResourceHandleToData( unnamed.vtex ) failed! Falling back to error texture!	
2024/09/06 08:16:53.8648	[engine/Engine] C:\build\_work\sbox\sbox\src\rendersystem\texturebase.cpp(3519):ResourceHandleToData( unnamed.vtex ) failed! Falling back to error texture!	
2024/09/06 08:16:53.8648	[engine/Engine] C:\build\_work\sbox\sbox\src\rendersystem\texturebase.cpp(3519):ResourceHandleToData( unnamed.vtex ) failed! Falling back to error texture!	
2024/09/06 08:16:53.8648	[engine/Engine] C:\build\_work\sbox\sbox\src\rendersystem\texturebase.cpp(3519):ResourceHandleToData( unnamed.vtex ) failed! Falling back to error texture!	
2024/09/06 08:16:53.8648	[engine/Engine] C:\build\_work\sbox\sbox\src\rendersystem\texturebase.cpp(3519):ResourceHandleToData( unnamed.vtex ) failed! Falling back to error texture!	
2024/09/06 08:16:53.8648	[engine/Engine] C:\build\_work\sbox\sbox\src\rendersystem\texturebase.cpp(3519):ResourceHandleToData( unnamed.vtex ) failed! Falling back to error texture!	
2024/09/06 08:16:53.8648	[engine/Engine] C:\build\_work\sbox\sbox\src\rendersystem\texturebase.cpp(3519):ResourceHandleToData( unnamed.vtex ) failed! Falling back to error texture!	
2024/09/06 08:16:53.8648	[engine/Engine] C:\build\_work\sbox\sbox\src\rendersystem\texturebase.cpp(3519):ResourceHandleToData( unnamed.vtex ) failed! Falling back to error texture!	
2024/09/06 08:16:53.8648	[engine/Engine] C:\build\_work\sbox\sbox\src\rendersystem\texturebase.cpp(3519):ResourceHandleToData( unnamed.vtex ) failed! Falling back to error texture!	
2024/09/06 08:16:53.8648	[engine/Engine] C:\build\_work\sbox\sbox\src\rendersystem\texturebase.cpp(3519):ResourceHandleToData( unnamed.vtex ) failed! Falling back to error texture!	
2024/09/06 08:16:53.8648	[engine/Engine] C:\build\_work\sbox\sbox\src\rendersystem\texturebase.cpp(3519):ResourceHandleToData( unnamed.vtex ) failed! Falling back to error texture!	
2024/09/06 08:16:53.8648	[engine/Engine] C:\build\_work\sbox\sbox\src\rendersystem\texturebase.cpp(3519):ResourceHandleToData( unnamed.vtex ) failed! Falling back to error texture!	
2024/09/06 08:16:53.8648	[engine/Engine] C:\build\_work\sbox\sbox\src\rendersystem\texturebase.cpp(3519):ResourceHandleToData( unnamed.vtex ) failed! Falling back to error texture!	
2024/09/06 08:16:53.8648	[engine/Engine] C:\build\_work\sbox\sbox\src\rendersystem\texturebase.cpp(3519):ResourceHandleToData( unnamed.vtex ) failed! Falling back to error texture!	
2024/09/06 08:16:53.8648	[engine/Engine] C:\build\_work\sbox\sbox\src\rendersystem\texturebase.cpp(3519):ResourceHandleToData( unnamed.vtex ) failed! Falling back to error texture!	
2024/09/06 08:16:53.8648	[engine/Engine] C:\build\_work\sbox\sbox\src\rendersystem\texturebase.cpp(3519):ResourceHandleToData( unnamed.vtex ) failed! Falling back to error texture!	
2024/09/06 08:16:53.8648	[engine/Engine] C:\build\_work\sbox\sbox\src\rendersystem\texturebase.cpp(3519):ResourceHandleToData( unnamed.vtex ) failed! Falling back to error texture!	
2024/09/06 08:16:53.8648	[engine/Engine] C:\build\_work\sbox\sbox\src\rendersystem\texturebase.cpp(3519):ResourceHandleToData( unnamed.vtex ) failed! Falling back to error texture!	
2024/09/06 08:16:53.8648	[engine/Engine] C:\build\_work\sbox\sbox\src\rendersystem\texturebase.cpp(3519):ResourceHandleToData( unnamed.vtex ) failed! Falling back to error texture!	
2024/09/06 08:16:53.8648	[engine/Engine] C:\build\_work\sbox\sbox\src\rendersystem\texturebase.cpp(3519):ResourceHandleToData( unnamed.vtex ) failed! Falling back to error texture!	
2024/09/06 08:16:53.8648	[engine/Engine] C:\build\_work\sbox\sbox\src\rendersystem\texturebase.cpp(3519):ResourceHandleToData( unnamed.vtex ) failed! Falling back to error texture!	
2024/09/06 08:16:53.8648	[engine/Engine] C:\build\_work\sbox\sbox\src\rendersystem\texturebase.cpp(3519):ResourceHandleToData( unnamed.vtex ) failed! Falling back to error texture!	
2024/09/06 08:16:53.8806	[engine/Engine] C:\build\_work\sbox\sbox\src\rendersystem\texturebase.cpp(3519):ResourceHandleToData( unnamed.vtex ) failed! Falling back to error texture!	
2024/09/06 08:16:53.8806	[engine/Engine] C:\build\_work\sbox\sbox\src\rendersystem\texturebase.cpp(3519):ResourceHandleToData( unnamed.vtex ) failed! Falling back to error texture!	
2024/09/06 08:16:53.8806	[engine/Engine] C:\build\_work\sbox\sbox\src\rendersystem\texturebase.cpp(3519):ResourceHandleToData( unnamed.vtex ) failed! Falling back to error texture!	
2024/09/06 08:16:53.8806	[engine/Engine] C:\build\_work\sbox\sbox\src\rendersystem\texturebase.cpp(3519):ResourceHandleToData( unnamed.vtex ) failed! Falling back to error texture!	
2024/09/06 08:16:53.8806	[engine/Engine] C:\build\_work\sbox\sbox\src\rendersystem\texturebase.cpp(3519):ResourceHandleToData( unnamed.vtex ) failed! Falling back to error texture!	
2024/09/06 08:16:53.8806	[engine/Engine] C:\build\_work\sbox\sbox\src\rendersystem\texturebase.cpp(3519):ResourceHandleToData( unnamed.vtex ) failed! Falling back to error texture!	
2024/09/06 08:16:53.8806	[engine/Engine] C:\build\_work\sbox\sbox\src\rendersystem\texturebase.cpp(3519):ResourceHandleToData( unnamed.vtex ) failed! Falling back to error texture!	
2024/09/06 08:16:53.8806	[engine/Engine] C:\build\_work\sbox\sbox\src\rendersystem\texturebase.cpp(3519):ResourceHandleToData( unnamed.vtex ) failed! Falling back to error texture!	
2024/09/06 08:16:53.8806	[engine/Engine] C:\build\_work\sbox\sbox\src\rendersystem\texturebase.cpp(3519):ResourceHandleToData( unnamed.vtex ) failed! Falling back to error texture!	
2024/09/06 08:16:53.8806	[engine/Engine] C:\build\_work\sbox\sbox\src\rendersystem\texturebase.cpp(3519):ResourceHandleToData( unnamed.vtex ) failed! Falling back to error texture!	
2024/09/06 08:16:53.8806	[engine/Engine] C:\build\_work\sbox\sbox\src\rendersystem\texturebase.cpp(3519):ResourceHandleToData( unnamed.vtex ) failed! Falling back to error texture!	
2024/09/06 08:16:53.8806	[engine/Engine] C:\build\_work\sbox\sbox\src\rendersystem\texturebase.cpp(3519):ResourceHandleToData( unnamed.vtex ) failed! Falling back to error texture!	
2024/09/06 08:16:53.8806	[engine/Engine] C:\build\_work\sbox\sbox\src\rendersystem\texturebase.cpp(3519):ResourceHandleToData( unnamed.vtex ) failed! Falling back to error texture!	
2024/09/06 08:16:53.8806	[engine/Engine] C:\build\_work\sbox\sbox\src\rendersystem\texturebase.cpp(3519):ResourceHandleToData( unnamed.vtex ) failed! Falling back to error texture!	
2024/09/06 08:16:53.8806	[engine/Engine] C:\build\_work\sbox\sbox\src\rendersystem\texturebase.cpp(3519):ResourceHandleToData( unnamed.vtex ) failed! Falling back to error texture!	
2024/09/06 08:16:53.8806	[engine/Engine] C:\build\_work\sbox\sbox\src\rendersystem\texturebase.cpp(3519):ResourceHandleToData( unnamed.vtex ) failed! Falling back to error texture!	
2024/09/06 08:16:53.8806	[engine/Engine] C:\build\_work\sbox\sbox\src\rendersystem\texturebase.cpp(3519):ResourceHandleToData( unnamed.vtex ) failed! Falling back to error texture!	
2024/09/06 08:16:53.8806	[engine/Engine] C:\build\_work\sbox\sbox\src\rendersystem\texturebase.cpp(3519):ResourceHandleToData( unnamed.vtex ) failed! Falling back to error texture!	
2024/09/06 08:16:53.8806	[engine/Engine] C:\build\_work\sbox\sbox\src\rendersystem\texturebase.cpp(3519):ResourceHandleToData( unnamed.vtex ) failed! Falling back to error texture!	
2024/09/06 08:16:53.8806	[engine/Engine] C:\build\_work\sbox\sbox\src\rendersystem\texturebase.cpp(3519):ResourceHandleToData( unnamed.vtex ) failed! Falling back to error texture!	
2024/09/06 08:16:53.8806	[engine/Engine] C:\build\_work\sbox\sbox\src\rendersystem\texturebase.cpp(3519):ResourceHandleToData( unnamed.vtex ) failed! Falling back to error texture!	
2024/09/06 08:16:53.8958	[engine/Engine] C:\build\_work\sbox\sbox\src\rendersystem\texturebase.cpp(3519):ResourceHandleToData( unnamed.vtex ) failed! Falling back to error texture!	
2024/09/06 08:16:53.8958	[engine/Engine] C:\build\_work\sbox\sbox\src\rendersystem\texturebase.cpp(3519):ResourceHandleToData( unnamed.vtex ) failed! Falling back to error texture!	
2024/09/06 08:16:53.8958	[engine/Engine] C:\build\_work\sbox\sbox\src\rendersystem\texturebase.cpp(3519):ResourceHandleToData( unnamed.vtex ) failed! Falling back to error texture!	
2024/09/06 08:16:53.8958	[engine/Engine] C:\build\_work\sbox\sbox\src\rendersystem\texturebase.cpp(3519):ResourceHandleToData( unnamed.vtex ) failed! Falling back to error texture!	
2024/09/06 08:16:53.8958	[engine/Engine] C:\build\_work\sbox\sbox\src\rendersystem\texturebase.cpp(3519):ResourceHandleToData( unnamed.vtex ) failed! Falling back to error texture!	
2024/09/06 08:16:53.8958	[engine/Engine] C:\build\_work\sbox\sbox\src\rendersystem\texturebase.cpp(3519):ResourceHandleToData( unnamed.vtex ) failed! Falling back to error texture!	
2024/09/06 08:16:53.8958	[engine/Engine] C:\build\_work\sbox\sbox\src\rendersystem\texturebase.cpp(3519):ResourceHandleToData( unnamed.vtex ) failed! Falling back to error texture!	
2024/09/06 08:16:53.8958	[engine/Engine] C:\build\_work\sbox\sbox\src\rendersystem\texturebase.cpp(3519):ResourceHandleToData( unnamed.vtex ) failed! Falling back to error texture!	
2024/09/06 08:16:53.8958	[engine/Engine] C:\build\_work\sbox\sbox\src\rendersystem\texturebase.cpp(3519):ResourceHandleToData( unnamed.vtex ) failed! Falling back to error texture!	
2024/09/06 08:16:53.8958	[engine/Engine] C:\build\_work\sbox\sbox\src\rendersystem\texturebase.cpp(3519):ResourceHandleToData( unnamed.vtex ) failed! Falling back to error texture!	
2024/09/06 08:16:53.8958	[engine/Engine] C:\build\_work\sbox\sbox\src\rendersystem\texturebase.cpp(3519):ResourceHandleToData( unnamed.vtex ) failed! Falling back to error texture!	
2024/09/06 08:16:53.8958	[engine/Engine] C:\build\_work\sbox\sbox\src\rendersystem\texturebase.cpp(3519):ResourceHandleToData( unnamed.vtex ) failed! Falling back to error texture!	
2024/09/06 08:16:53.8958	[engine/Engine] C:\build\_work\sbox\sbox\src\rendersystem\texturebase.cpp(3519):ResourceHandleToData( unnamed.vtex ) failed! Falling back to error texture!	
2024/09/06 08:16:53.8958	[engine/Engine] C:\build\_work\sbox\sbox\src\rendersystem\texturebase.cpp(3519):ResourceHandleToData( unnamed.vtex ) failed! Falling back to error texture!	
2024/09/06 08:16:53.8958	[engine/Engine] C:\build\_work\sbox\sbox\src\rendersystem\texturebase.cpp(3519):ResourceHandleToData( unnamed.vtex ) failed! Falling back to error texture!	
2024/09/06 08:16:53.8958	[engine/Engine] C:\build\_work\sbox\sbox\src\rendersystem\texturebase.cpp(3519):ResourceHandleToData( unnamed.vtex ) failed! Falling back to error texture!	
2024/09/06 08:16:53.8958	[engine/Engine] C:\build\_work\sbox\sbox\src\rendersystem\texturebase.cpp(3519):ResourceHandleToData( unnamed.vtex ) failed! Falling back to error texture!	
2024/09/06 08:16:53.8958	[engine/Engine] C:\build\_work\sbox\sbox\src\rendersystem\texturebase.cpp(3519):ResourceHandleToData( unnamed.vtex ) failed! Falling back to error texture!	
2024/09/06 08:16:53.8958	[engine/Engine] C:\build\_work\sbox\sbox\src\rendersystem\texturebase.cpp(3519):ResourceHandleToData( unnamed.vtex ) failed! Falling back to error texture!	
2024/09/06 08:16:53.8958	[engine/Engine] C:\build\_work\sbox\sbox\src\rendersystem\texturebase.cpp(3519):ResourceHandleToData( unnamed.vtex ) failed! Falling back to error texture!	
2024/09/06 08:16:53.8958	[engine/Engine] C:\build\_work\sbox\sbox\src\rendersystem\texturebase.cpp(3519):ResourceHandleToData( unnamed.vtex ) failed! Falling back to error texture!	
2024/09/06 08:16:53.8958	[engine/Engine] C:\build\_work\sbox\sbox\src\rendersystem\texturebase.cpp(3519):ResourceHandleToData( unnamed.vtex ) failed! Falling back to error texture!	
2024/09/06 08:16:53.8958	[engine/Engine] C:\build\_work\sbox\sbox\src\rendersystem\texturebase.cpp(3519):ResourceHandleToData( unnamed.vtex ) failed! Falling back to error texture!	
2024/09/06 08:16:53.9122	[engine/Engine] C:\build\_work\sbox\sbox\src\rendersystem\texturebase.cpp(3519):ResourceHandleToData( unnamed.vtex ) failed! Falling back to error texture!	
2024/09/06 08:16:53.9122	[engine/Engine] C:\build\_work\sbox\sbox\src\rendersystem\texturebase.cpp(3519):ResourceHandleToData( unnamed.vtex ) failed! Falling back to error texture!	
2024/09/06 08:16:53.9122	[engine/Engine] C:\build\_work\sbox\sbox\src\rendersystem\texturebase.cpp(3519):ResourceHandleToData( unnamed.vtex ) failed! Falling back to error texture!	
2024/09/06 08:16:53.9122	[engine/Engine] C:\build\_work\sbox\sbox\src\rendersystem\texturebase.cpp(3519):ResourceHandleToData( unnamed.vtex ) failed! Falling back to error texture!	
2024/09/06 08:16:53.9122	[engine/Engine] C:\build\_work\sbox\sbox\src\rendersystem\texturebase.cpp(3519):ResourceHandleToData( unnamed.vtex ) failed! Falling back to error texture!	
2024/09/06 08:16:53.9122	[engine/Engine] C:\build\_work\sbox\sbox\src\rendersystem\texturebase.cpp(3519):ResourceHandleToData( unnamed.vtex ) failed! Falling back to error texture!	
2024/09/06 08:16:53.9122	[engine/Engine] C:\build\_work\sbox\sbox\src\rendersystem\texturebase.cpp(3519):ResourceHandleToData( unnamed.vtex ) failed! Falling back to error texture!	
2024/09/06 08:16:53.9122	[engine/Engine] C:\build\_work\sbox\sbox\src\rendersystem\texturebase.cpp(3519):ResourceHandleToData( unnamed.vtex ) failed! Falling back to error texture!	
2024/09/06 08:16:53.9122	[engine/Engine] C:\build\_work\sbox\sbox\src\rendersystem\texturebase.cpp(3519):ResourceHandleToData( unnamed.vtex ) failed! Falling back to error texture!	
2024/09/06 08:16:53.9122	[engine/Engine] C:\build\_work\sbox\sbox\src\rendersystem\texturebase.cpp(3519):ResourceHandleToData( unnamed.vtex ) failed! Falling back to error texture!	
2024/09/06 08:16:53.9122	[engine/Engine] C:\build\_work\sbox\sbox\src\rendersystem\texturebase.cpp(3519):ResourceHandleToData( unnamed.vtex ) failed! Falling back to error texture!	
2024/09/06 08:16:53.9122	[engine/Engine] C:\build\_work\sbox\sbox\src\rendersystem\texturebase.cpp(3519):ResourceHandleToData( unnamed.vtex ) failed! Falling back to error texture!	
2024/09/06 08:16:53.9122	[engine/Engine] C:\build\_work\sbox\sbox\src\rendersystem\texturebase.cpp(3519):ResourceHandleToData( unnamed.vtex ) failed! Falling back to error texture!	
2024/09/06 08:16:53.9122	[engine/Engine] C:\build\_work\sbox\sbox\src\rendersystem\texturebase.cpp(3519):ResourceHandleToData( unnamed.vtex ) failed! Falling back to error texture!	
2024/09/06 08:16:53.9122	[engine/Engine] C:\build\_work\sbox\sbox\src\rendersystem\texturebase.cpp(3519):ResourceHandleToData( unnamed.vtex ) failed! Falling back to error texture!	
2024/09/06 08:16:53.9122	[engine/Engine] C:\build\_work\sbox\sbox\src\rendersystem\texturebase.cpp(3519):ResourceHandleToData( unnamed.vtex ) failed! Falling back to error texture!	
2024/09/06 08:16:53.9122	[engine/Engine] C:\build\_work\sbox\sbox\src\rendersystem\texturebase.cpp(3519):ResourceHandleToData( unnamed.vtex ) failed! Falling back to error texture!	
2024/09/06 08:16:53.9122	[engine/Engine] C:\build\_work\sbox\sbox\src\rendersystem\texturebase.cpp(3519):ResourceHandleToData( unnamed.vtex ) failed! Falling back to error texture!	
2024/09/06 08:16:53.9122	[engine/Engine] C:\build\_work\sbox\sbox\src\rendersystem\texturebase.cpp(3519):ResourceHandleToData( unnamed.vtex ) failed! Falling back to error texture!	
2024/09/06 08:16:53.9122	[engine/Engine] C:\build\_work\sbox\sbox\src\rendersystem\texturebase.cpp(3519):ResourceHandleToData( unnamed.vtex ) failed! Falling back to error texture!	
2024/09/06 08:16:53.9122	[engine/Engine] C:\build\_work\sbox\sbox\src\rendersystem\texturebase.cpp(3519):ResourceHandleToData( unnamed.vtex ) failed! Falling back to error texture!	
2024/09/06 08:16:53.9274	[engine/Engine] C:\build\_work\sbox\sbox\src\rendersystem\texturebase.cpp(3519):ResourceHandleToData( unnamed.vtex ) failed! Falling back to error texture!	
2024/09/06 08:16:53.9274	[engine/Engine] C:\build\_work\sbox\sbox\src\rendersystem\texturebase.cpp(3519):ResourceHandleToData( unnamed.vtex ) failed! Falling back to error texture!	
2024/09/06 08:16:53.9274	[engine/Engine] C:\build\_work\sbox\sbox\src\rendersystem\texturebase.cpp(3519):ResourceHandleToData( unnamed.vtex ) failed! Falling back to error texture!	
2024/09/06 08:16:53.9274	[engine/Engine] C:\build\_work\sbox\sbox\src\rendersystem\texturebase.cpp(3519):ResourceHandleToData( unnamed.vtex ) failed! Falling back to error texture!	
2024/09/06 08:16:53.9274	[engine/Engine] C:\build\_work\sbox\sbox\src\rendersystem\texturebase.cpp(3519):ResourceHandleToData( unnamed.vtex ) failed! Falling back to error texture!	
2024/09/06 08:16:53.9274	[engine/Engine] C:\build\_work\sbox\sbox\src\rendersystem\texturebase.cpp(3519):ResourceHandleToData( unnamed.vtex ) failed! Falling back to error texture!	
2024/09/06 08:16:53.9274	[engine/Engine] C:\build\_work\sbox\sbox\src\rendersystem\texturebase.cpp(3519):ResourceHandleToData( unnamed.vtex ) failed! Falling back to error texture!	
2024/09/06 08:16:53.9274	[engine/Engine] C:\build\_work\sbox\sbox\src\rendersystem\texturebase.cpp(3519):ResourceHandleToData( unnamed.vtex ) failed! Falling back to error texture!	
2024/09/06 08:16:53.9274	[engine/Engine] C:\build\_work\sbox\sbox\src\rendersystem\texturebase.cpp(3519):ResourceHandleToData( unnamed.vtex ) failed! Falling back to error texture!	
2024/09/06 08:16:53.9274	[engine/Engine] C:\build\_work\sbox\sbox\src\rendersystem\texturebase.cpp(3519):ResourceHandleToData( unnamed.vtex ) failed! Falling back to error texture!	
2024/09/06 08:16:53.9274	[engine/Engine] C:\build\_work\sbox\sbox\src\rendersystem\texturebase.cpp(3519):ResourceHandleToData( unnamed.vtex ) failed! Falling back to error texture!	
2024/09/06 08:16:53.9274	[engine/Engine] C:\build\_work\sbox\sbox\src\rendersystem\texturebase.cpp(3519):ResourceHandleToData( unnamed.vtex ) failed! Falling back to error texture!	
2024/09/06 08:16:53.9274	[engine/Engine] C:\build\_work\sbox\sbox\src\rendersystem\texturebase.cpp(3519):ResourceHandleToData( unnamed.vtex ) failed! Falling back to error texture!	
2024/09/06 08:16:53.9274	[engine/Engine] C:\build\_work\sbox\sbox\src\rendersystem\texturebase.cpp(3519):ResourceHandleToData( unnamed.vtex ) failed! Falling back to error texture!	
2024/09/06 08:16:53.9274	[engine/Engine] C:\build\_work\sbox\sbox\src\rendersystem\texturebase.cpp(3519):ResourceHandleToData( unnamed.vtex ) failed! Falling back to error texture!	
2024/09/06 08:16:53.9274	[engine/Engine] C:\build\_work\sbox\sbox\src\rendersystem\texturebase.cpp(3519):ResourceHandleToData( unnamed.vtex ) failed! Falling back to error texture!	
2024/09/06 08:16:53.9274	[engine/Engine] C:\build\_work\sbox\sbox\src\rendersystem\texturebase.cpp(3519):ResourceHandleToData( unnamed.vtex ) failed! Falling back to error texture!	
2024/09/06 08:16:53.9274	[engine/Engine] C:\build\_work\sbox\sbox\src\rendersystem\texturebase.cpp(3519):ResourceHandleToData( unnamed.vtex ) failed! Falling back to error texture!	
2024/09/06 08:16:53.9274	[engine/Engine] C:\build\_work\sbox\sbox\src\rendersystem\texturebase.cpp(3519):ResourceHandleToData( unnamed.vtex ) failed! Falling back to error texture!	
2024/09/06 08:16:53.9274	[engine/Engine] C:\build\_work\sbox\sbox\src\rendersystem\texturebase.cpp(3519):ResourceHandleToData( unnamed.vtex ) failed! Falling back to error texture!	
2024/09/06 08:16:53.9274	[engine/Engine] C:\build\_work\sbox\sbox\src\rendersystem\texturebase.cpp(3519):ResourceHandleToData( unnamed.vtex ) failed! Falling back to error texture!	
2024/09/06 08:16:53.9274	[engine/Engine] C:\build\_work\sbox\sbox\src\rendersystem\texturebase.cpp(3519):ResourceHandleToData( unnamed.vtex ) failed! Falling back to error texture!	
2024/09/06 08:16:53.9429	[engine/Engine] C:\build\_work\sbox\sbox\src\rendersystem\texturebase.cpp(3519):ResourceHandleToData( unnamed.vtex ) failed! Falling back to error texture!	
2024/09/06 08:16:53.9429	[engine/Engine] C:\build\_work\sbox\sbox\src\rendersystem\texturebase.cpp(3519):ResourceHandleToData( unnamed.vtex ) failed! Falling back to error texture!	
2024/09/06 08:16:53.9429	[engine/Engine] C:\build\_work\sbox\sbox\src\rendersystem\texturebase.cpp(3519):ResourceHandleToData( unnamed.vtex ) failed! Falling back to error texture!	
2024/09/06 08:16:53.9429	[engine/Engine] C:\build\_work\sbox\sbox\src\rendersystem\texturebase.cpp(3519):ResourceHandleToData( unnamed.vtex ) failed! Falling back to error texture!	
2024/09/06 08:16:53.9429	[engine/Engine] C:\build\_work\sbox\sbox\src\rendersystem\texturebase.cpp(3519):ResourceHandleToData( unnamed.vtex ) failed! Falling back to error texture!	
2024/09/06 08:16:53.9429	[engine/Engine] C:\build\_work\sbox\sbox\src\rendersystem\texturebase.cpp(3519):ResourceHandleToData( unnamed.vtex ) failed! Falling back to error texture!	
2024/09/06 08:16:53.9429	[engine/Engine] C:\build\_work\sbox\sbox\src\rendersystem\texturebase.cpp(3519):ResourceHandleToData( unnamed.vtex ) failed! Falling back to error texture!	
2024/09/06 08:16:53.9429	[engine/Engine] C:\build\_work\sbox\sbox\src\rendersystem\texturebase.cpp(3519):ResourceHandleToData( unnamed.vtex ) failed! Falling back to error texture!	
2024/09/06 08:16:53.9429	[engine/Engine] C:\build\_work\sbox\sbox\src\rendersystem\texturebase.cpp(3519):ResourceHandleToData( unnamed.vtex ) failed! Falling back to error texture!	
2024/09/06 08:16:53.9429	[engine/Engine] C:\build\_work\sbox\sbox\src\rendersystem\texturebase.cpp(3519):ResourceHandleToData( unnamed.vtex ) failed! Falling back to error texture!	
2024/09/06 08:16:53.9429	[engine/Engine] C:\build\_work\sbox\sbox\src\rendersystem\texturebase.cpp(3519):ResourceHandleToData( unnamed.vtex ) failed! Falling back to error texture!	
2024/09/06 08:16:53.9429	[engine/Engine] C:\build\_work\sbox\sbox\src\rendersystem\texturebase.cpp(3519):ResourceHandleToData( unnamed.vtex ) failed! Falling back to error texture!	
2024/09/06 08:16:53.9429	[engine/Engine] C:\build\_work\sbox\sbox\src\rendersystem\texturebase.cpp(3519):ResourceHandleToData( unnamed.vtex ) failed! Falling back to error texture!	
2024/09/06 08:16:53.9429	[engine/Engine] C:\build\_work\sbox\sbox\src\rendersystem\texturebase.cpp(3519):ResourceHandleToData( unnamed.vtex ) failed! Falling back to error texture!	
2024/09/06 08:16:53.9429	[engine/Engine] C:\build\_work\sbox\sbox\src\rendersystem\texturebase.cpp(3519):ResourceHandleToData( unnamed.vtex ) failed! Falling back to error texture!	
2024/09/06 08:16:53.9429	[engine/Engine] C:\build\_work\sbox\sbox\src\rendersystem\texturebase.cpp(3519):ResourceHandleToData( unnamed.vtex ) failed! Falling back to error texture!	
2024/09/06 08:16:53.9429	[engine/Engine] C:\build\_work\sbox\sbox\src\rendersystem\texturebase.cpp(3519):ResourceHandleToData( unnamed.vtex ) failed! Falling back to error texture!	
2024/09/06 08:16:53.9429	[engine/Engine] C:\build\_work\sbox\sbox\src\rendersystem\texturebase.cpp(3519):ResourceHandleToData( unnamed.vtex ) failed! Falling back to error texture!	
2024/09/06 08:16:53.9429	[engine/Engine] C:\build\_work\sbox\sbox\src\rendersystem\texturebase.cpp(3519):ResourceHandleToData( unnamed.vtex ) failed! Falling back to error texture!	
2024/09/06 08:16:53.9429	[engine/Engine] C:\build\_work\sbox\sbox\src\rendersystem\texturebase.cpp(3519):ResourceHandleToData( unnamed.vtex ) failed! Falling back to error texture!	
2024/09/06 08:16:59.2186	[engine/SceneSystem] CSceneSystem::CompletionWaitJob(6639): Waited 500 ms for jobs to complete. Attempt to drain windows message queue.

**Comment by samzanemesis** [comment]
That message is unrelated, I'll have another look, can you send me your scene @dch-GH ?

**Comment by dch-GH** [comment]
> That message is unrelated, I'll have another look, can you send me your scene @dch-GH ?

Sure: <https://github.com/dch-GH/multicam>. Just open the scene `test.guard_zoo`

**Comment by samzanemesis** [comment]
I really can't get this to replicate but seeing this being reported, still looking into it
