### ISSUE TITLE
Removing non-existent PhysicsShape hard crashes the game

### ISSUE THREAD

**Issue by Leafdroid** [Facepunch/sbox-issues#667]
**Describe the bug**

Removing the same PhysicsShape again after it has already been removed once will hard crash the game with the following error;

> Interop	Index was out of range. Must be non-negative and less than the size of the collection. (Parameter 'index')	System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection. (Parameter 'index')
   at Sandbox.HandleIndex.Delete(IntPtr ptr, Int32 handle) in C:\buildbot\work\sbox\sbox\engine\Sandbox.Engine\Interop\Handle.cs:line 80
   at Managed.SourceServer.Exports.Sandboserver_Physcs_f7(IntPtr ptr, Int32 idx) in C:\buildbot\work\sbox\sbox\engine\Sandbox.Game\Interop.Server.cs:line 6289

**To Reproduce**

```cs
[ServerCmd( "crash", Help = "Crashes your game" )]
public static void CrashGame()
{
	// note that this works for any physicsbody, not just the world
	PhysicsBody body = PhysicsWorld.WorldBody;

	// create the shape
	PhysicsShape shape = body.AddSphereShape( Vector3.Zero, 4f, false );

	// remove the shape from the body (and existence)
	body.RemoveShape( shape );

	// PhysicsShape is not recognized as null after being removed so this does nothing
	if ( body == null )
		return;

	// attempt to remove the shape again and well... death.
	body.RemoveShape( shape );
}
```

**Expected behavior**

Throw an error that points you to the faulty removal attempt / make the PhysicsShape null after removal. (I crashed myself _quite a few_ times trying to figure out what was causing this crash)

**Comment by aylaylay** [comment]
I have pushed a fix to invalidate the shape when removed and throws an exception when trying to remove an invalid shape. Please close the issue if it works and you're happy with it.

**Comment by Leafdroid** [comment]
Game still appears to crash on the latest version when the ServerCmd example above is ran, doesn't seem to behave any different from before.

**Comment by aylaylay** [comment]
Just tested it on the steam version, works for me. Try renaming the command to something other than "crash" I suspect that it's running the engine crash command.. which crashes the game.

**Comment by Leafdroid** [comment]
Yep, I just realized... It is indeed working like it should.
