### ISSUE TITLE
Publishing your project now causes errors while joining via new instance

### ISSUE THREAD

**Issue by ChillBoxServers** [Facepunch/sbox-issues#6984]
### Describe the bug

After you publish a project now if you join via new instance you get loads of errors.

### To Reproduce

1. Create a new project
2. Add network helper
3. Join via new instance, no errors
4. Publish the project
5. Join via new instance, errors

### Expected behavior

To not have errors

### Media/Files

![Image](https://github.com/user-attachments/assets/3f646061-8239-4852-be67-7baf6a5a0798)

**Comment by garrynewman** [comment]
Do you have the log file for this one?

**Comment by ChillBoxServers** [comment]
[sbox.log](https://github.com/user-attachments/files/17849706/sbox.log)

**Comment by ChillBoxServers** [comment]
also in a new project there is no game menu at all till you publish it

**Comment by Metapyziks** [comment]
I haven't been able to repro this yet, both when publishing a new project and an update to an existing one. It might be specific to your project. Would you be okay giving me access?

**Comment by Metapyziks** [comment]
I've pushed a possible fix, could you let me know if you see this warning in your console when joining as a new instance:

```
Encountered a JsonTypeInfo, did Json serialization occur during hotload?
```

**Comment by ChillBoxServers** [comment]
it still happens.

https://streamable.com/9jp18h

its not just one of my projects its all with networking and any new project i create. could this be because i use more than one organization?

**Comment by Metapyziks** [comment]
Looks like you're on a build from yesterday (`ee7f170e`). My fix should be on the `staging` beta branch on Steam, I guess that doesn't get pushed to `default` automatically any more. If you still get the bug there, could you send me the new log file please. Thanks!
