### ISSUE TITLE
Maps not updating in editor after recompile

### ISSUE THREAD

**Issue by ScoutWozniak** [Facepunch/sbox-issues#7493]
### Describe the bug

When I compile a map in hammer, any map instances do not show the updated version until a restart.  The only exception to this is some game objects are updated, but the geometry is not updated until the editor is restarted.

### To Reproduce

1. Compile a map
2. Try and view the changes in the scene 

### Expected behavior

The map should be fully updated in the scene editor with the latest version.

**Comment by ScoutWozniak** [comment]
Update: so it seems to be specifically for all maps in this project as compiling a map in an older project still updates it properly.  I've attached the map file here in case it gives any information (though it seems to be project wide this time)

[kitchen_collection.zip](https://github.com/user-attachments/files/18631362/kitchen_collection.zip)

**Comment by Nolankicks** [comment]
Seems to only be for prefabs fyi

**Comment by lolleko** [comment]
Did this started happen recently or has it always been the case?

**Comment by fantasticaneer** [comment]
> Did this started happen recently or has it always been the case?

It's been been an issue the whole time I've been trying to work on this project, but I don't recall if it was a problem in the past.

**Comment by lolleko** [comment]
How long have you been working on your project😅 ?

**Comment by Nolankicks** [comment]
3-4 weeks

**Comment by solwllms** [comment]
Fixed a case where it wouldn't reload maps that had failed to load previously, but _seems_ to be working ok otherwise with the map you attached and others.

Can you give it another whirl, and if you're still having trouble could you send the project if that's a reliable repro?

**Comment by ScoutWozniak** [comment]
Sadly its still not reloading, whats the best way to send over the project for you to take a look at it?

**Comment by fantasticaneer** [comment]
This is specifically an issue with map instances inside prefabs, I think @solwllms

**Comment by aylaylay** [comment]
Should be fixed now

**Comment by ScoutWozniak** [comment]
Yep it fully works I hope they give you several raises now
