### ISSUE TITLE
Ultrawide monitor issues

### ISSUE THREAD

**Issue by matekdev** [Facepunch/sbox-issues#7910]
### Describe the bug

In windows, you can make it so that your bottom task bar will hide if it isn't being used. It used to be the case that when you had the s&box editor full screen, you could move your mouse to the bottom to reveal it. This is no longer the case about a week or so ago.

I'm on ultrawide with 125% windows scaling.

### To Reproduce

https://github.com/user-attachments/assets/2a559c02-9e03-4248-b485-635a4af5501f

![Image](https://github.com/user-attachments/assets/a0002ed2-ee84-437f-83e5-6bc3596ec4f7)

### Expected behavior

You should be able to reveal the windows task bar

**Comment by xezno** [comment]
I have a feeling that it's because we unset the margin for the window, so Windows thinks it's 8 pixels bigger than it is all the way round

**Comment by matekdev** [comment]
I'm getting other weird behaviour as well
1. It looks like there is extra padding on the right side of my screen, for instance, if I move my mouse to the top right of the screen I'm unable to hit the close button for the s&box window (even when it is full screen). All other windows apps do not behave like this
2. If I hit the middle fullscreen button, it doesn't actually full screen, it snaps to weird parts of my screen

**Comment by matekdev** [comment]
https://github.com/user-attachments/assets/e311b294-0521-4b69-ac53-eead612f9f89

**Comment by matekdev** [comment]
https://github.com/user-attachments/assets/005c05bb-8741-4508-8f55-c74aa4abaa93

**Comment by SturnusA** [comment]
I'm also getting the autohidden taskbar not popping up when s&box is fullscreened, and the maximize button not applying maximum window size until the third click.

**Comment by xezno** [comment]
I pushed something that may or may not fix the close button problem, give it a shot

**Comment by matekdev** [comment]
I'm still getting all issues mentioned originally.  Let me know if you need any other details, the monitor I'm using is a AW3423DWF.

**Comment by SturnusA** [comment]
I'm no longer getting the maximize issues so it must be related to the higher ppi displays? my monitor is sub 100, where as @matekdev has above 100.

The task bar still has the issue of not reappearing when the editor is maximized.

**Comment by matekdev** [comment]
https://github.com/user-attachments/assets/34b36a11-f4e1-4b60-a96a-672982e1eaad
HC3 is busted as well, looks like it's related to my edge issue mentioned above.

**Comment by matekdev** [comment]
It looks like the windows task bar works after you launch, full screen the editor, and then swap in and out of the editor. Still pretty weird. The rest of the issues still occur.

**Comment by matekdev** [comment]
<img width="3439" height="1439" alt="Image" src="https://github.com/user-attachments/assets/b48a8934-3437-498b-8b42-9d648a93f33d" />
My UI gets cut off now at the top when in 1080p mode

**Comment by AustinDotCodes** [comment]
since this is still alive, posting another video of the maximize issues somehow regressing. found a much more solid way to reproduce though! if you resize the window and then resize it again to it's minimum size, it won't allow you to maximize to fill the screen, it'll just snap it to the top left of the current monitor. vid attached for reference.

https://github.com/user-attachments/assets/acbf09a6-eba8-4a93-b649-a990521bca57

**Comment by AustinDotCodes** [comment]
i don't think the maximize was ever a ultrawide only issue, it was just mentioned that it was occurring on an ultrawide, if you prefer i can make a new issue with the maximize issue separately.
