### ISSUE TITLE
Stylesheet parsing error after changing regional decimal symbol

### ISSUE THREAD

**Issue by araghon007** [Facepunch/sbox-issues#905]
**Describe the bug**
Manually changing the decimal symbol in regional settings causes an incorrect string format error to occur while parsing the main menu stylesheet. Works fine if you change the regional format to a format that has a different decimal symbol by default.

**To Reproduce**

1. Go to regional settings using the control panel
2. Click on Additional settings
3. Change the Decimal symbol to ,
4. Launch the game and enjoy a black screen

**Screenshots**
![image](https://user-images.githubusercontent.com/10870921/132961128-4b08df05-2068-4f55-b8ab-e36bd813b6c5.png)
![image](https://user-images.githubusercontent.com/10870921/132961143-b6312d19-190f-4cdb-ac2b-40e400501b7b.png)

Log file:
[Log.28.log](https://github.com/Facepunch/sbox-issues/files/7148494/Log.28.log)

The reason I have to do this manually is to keep English day names, while being able to use the . (, on my keyboard layout) key on my numpad for inputting decimal numbers into some stubborn programs, so I don't think a lot of people would have this kind of setup.

**Comment by handsomematt** [comment]
Should be fixed now.

**Comment by araghon007** [comment]
Hello, thank you for trying to fix this issue. Unfortunately, it seems that either the Steam version didn't yet receive this change, or it's not yet fixed. Still getting a similar issue, though the line numbers seem to have changed, and I'm also getting an "Expecting time in transition" error.
[Log.88.log](https://github.com/Facepunch/sbox-issues/files/7730237/Log.88.log)

**Comment by handsomematt** [comment]
Added the same formatting to time parser, should be good now.

**Comment by araghon007** [comment]
I'm sorry to say that the issue still persists. Sorry for not responding earlier, I was away from my computer for a few days.

The time parser errors were fixed, but the rest of the errors remain
[Log.log](https://github.com/Facepunch/sbox-issues/files/7789221/Log.log)

Still, thanks a lot for trying to fix this, I'm just hoping the fixes wouldn't cause parsing issues elsewhere sometime in the future, or worse.

**Comment by handsomematt** [comment]
Thanks for the updated log, sadly I'm unable to reproduce the errors on my machine from changing my settings, so your feedback is vital thanks.

Hopefully I've now fixed the remaining places in the CSS parser, let me know if there's any more issues though.

**Comment by araghon007** [comment]
That worked. Thanks!
